# File: ./R/impl_account_sub_account.R

box::use(
    ./helpers_api[ auto_paginate, build_headers, process_kucoin_response ],
    ./utils[ build_query, get_base_url ]
)

#' Add SubAccount Implementation
#'
#' This asynchronous function creates a new sub‐account on KuCoin by sending a POST request to the 
#' `/api/v2/sub/user/created` endpoint. Sub‐accounts are used to segregate trading activities or to allow 
#' multiple users within the same master account to operate independently. This function handles the entire 
#' process—from constructing the request body and generating the appropriate authentication headers to sending 
#' the request and processing the response. On success, it returns a `data.table` with key details about the 
#' newly created sub‐account.
#'
#' ## Endpoint Overview
#'
#' **Endpoint URL:**  
#' `POST https://api.kucoin.com/api/v2/sub/user/created`
#'
#' **Purpose:**  
#' This endpoint is used to add a new sub-account under a master KuCoin account. Sub-accounts can be used to manage 
#' different trading strategies or for delegating trading activities. They are particularly useful in institutional 
#' or multi-user environments.
#'
#' **Request Requirements:**  
#' - The request must be authenticated using the master account's API credentials.
#' - The POST request body must be in JSON format.
#'
#' **Response Details:**  
#' On success, the API returns a JSON response with a status code of `"200000"`, and the `data` object contains 
#' details about the newly created sub-account, including its unique identifier (uid), name, remarks, and permission type.
#'
#' ## Parameters
#'
#' - **config**:  
#'   A list containing API configuration parameters. This list must include:
#'   - `api_key`: Your KuCoin API key.
#'   - `api_secret`: Your KuCoin API secret.
#'   - `api_passphrase`: Your KuCoin API passphrase.
#'   - `base_url`: The base URL for the API (typically `"https://api.kucoin.com"`).
#'   - `key_version`: The version of the API key (usually `"2"`).
#'
#' - **password**:  
#'   A string representing the sub‐account password.  
#'   **Requirements:**  
#'   - Must be between 7 and 24 characters in length.
#'   - Must contain both letters and numbers.
#'
#' - **subName**:  
#'   A string representing the desired sub‐account name.  
#'   **Requirements:**  
#'   - Must be between 7 and 32 characters.
#'   - Must contain at least one letter and one number.
#'   - Must not contain any spaces.
#'
#' - **access**:  
#'   A string representing the permission type for the sub‐account.  
#'   **Allowed Values:**  
#'   - `"Spot"`
#'   - `"Futures"`
#'   - `"Margin"`
#'
#' - **remarks**:  
#'   (Optional) A string containing remarks or notes about the sub‐account.  
#'   **Requirements:**  
#'   - If provided, must be between 1 and 24 characters.
#'
#' ## Return Value
#'
#' Returns a promise that resolves to a `data.table` containing the sub‐account details. The returned table 
#' will include at least the following columns:
#' - **uid**: The unique identifier for the sub-account.
#' - **subName**: The name of the sub-account.
#' - **remarks**: Any remarks or notes provided.
#' - **access**: The permission type granted to the sub-account.
#'
#' ## Detailed Workflow
#'
#' 1. **URL Construction:**  
#'    The function retrieves the base URL from the `config` and appends the endpoint `/api/v2/sub/user/created` to construct the full URL.
#'
#' 2. **Request Body Preparation:**  
#'    The function creates a list containing the required parameters (`password`, `subName`, `access`).  
#'    - If the optional parameter `remarks` is provided, it is added to the list.
#'    - The list is then converted to JSON format using `jsonlite::toJSON()` with `auto_unbox = TRUE` to ensure proper formatting.
#'
#' 3. **Header Preparation:**  
#'    Authentication headers are generated by calling `build_headers()` asynchronously. These headers include 
#'    the necessary signature and timestamp required by the KuCoin API.
#'
#' 4. **API Request:**  
#'    The function sends a POST request using `POST()` with the constructed URL, headers, and JSON body. A timeout 
#'    of 3 seconds is applied to the request.
#'
#' 5. **Response Handling:**  
#'    The response is read and parsed from JSON into an R object. The function checks for both HTTP and API-level 
#'    errors:
#'    - If the HTTP status code is not 200, an error is raised.
#'    - If the API returns a code other than `"200000"`, an error is raised with the message provided in the response.
#'
#' 6. **Result Conversion:**  
#'    On success, the `data` field of the response is converted to a `data.table` and returned.
#'
#' ## Example Usage
#'
#' ```r
#' \dontrun{
#'   # Assume `config` is already defined with the necessary API credentials.
#'   coro::run(function() {
#'       result <- await(add_subaccount_impl(
#'           config,
#'           password = "1234567",
#'           subName = "Name1234567",
#'           access = "Spot",
#'           remarks = "Test sub-account"
#'       ))
#'       print(result)
#'   })
#' }
#' ```
#'
#' @export
#' @md
add_subaccount_impl <- coro::async(function(config, password, subName, access, remarks = NULL) {
    tryCatch({
        base_url <- get_base_url(config)
        endpoint <- "/api/v2/sub/user/created"
        method <- "POST"
        body_list <- list(
            password = password,
            subName = subName,
            access = access
        )
        if (!is.null(remarks)) {
            body_list$remarks <- remarks
        }
        body <- jsonlite::toJSON(body_list, auto_unbox = TRUE)
        headers <- await(build_headers(method, endpoint, body, config))
        url <- paste0(base_url, endpoint)
        response <- POST(url, headers, body = body, encode = "raw", timeout(3))
        response_text <- httr::content(response, as = "text", encoding = "UTF-8")
        parsed_response <- jsonlite::fromJSON(response_text)
        if (httr::status_code(response) != 200) {
            rlang::abort(paste("HTTP request failed with status code", httr::status_code(response), "for URL:", url))
        }
        if (as.character(parsed_response$code) != "200000") {
            error_msg <- "No error message provided."
            if ("msg" %in% names(parsed_response)) {
                error_msg <- parsed_response$msg
            }
            rlang::abort(paste("KuCoin API returned an error:", parsed_response$code, "-", error_msg))
        }
        result <- NULL
        if ("data" %in% names(parsed_response)) {
            result <- data.table::as.data.table(parsed_response$data)
        } else {
            result <- parsed_response
        }
        return(result)
    }, error = function(e) {
        abort(paste("Error in add_subaccount_impl:", conditionMessage(e)))
    })
})

#' Get SubAccount List - Summary Info Implementation
#'
#' This asynchronous function retrieves a paginated list of sub-accounts from KuCoin using the generic pagination helper.
#' Users can specify the page size and the maximum number of pages to fetch. By default, it fetches all pages with a page size of 100.
#' After aggregation, if a "createdAt" column is present, its values (in milliseconds) are converted to POSIXct datetime objects.
#'
#' @param config A list containing API configuration parameters.
#' @param page_size An integer specifying the number of results per page (default is 100).
#' @param max_pages The maximum number of pages to fetch. Use Inf to fetch all pages (default is Inf).
#'
#' @return A promise that resolves to a data.table containing the aggregated sub-account summary information,
#'         with the "createdAt" column converted to datetime (if present).
#'
#' @examples
#' \dontrun{
#'   # Fetch all sub-account summaries with page size 100:
#'   dt <- await(get_subaccount_list_summary_impl(config))
#'
#'   # Fetch only 3 pages with a page size of 50:
#'   dt <- await(get_subaccount_list_summary_impl(config, page_size = 50, max_pages = 3))
#' }
#'
#' @export
get_subaccount_list_summary_impl <- coro::async(function(config, page_size = 100, max_pages = Inf) {
    tryCatch({
        fetch_page <- coro::async(function(query) {
            base_url <- get_base_url(config)
            endpoint <- "/api/v2/sub/user"
            method <- "GET"
            body <- ""
            qs <- build_query(query)
            full_endpoint <- paste0(endpoint, qs)
            headers <- await(build_headers(method, full_endpoint, body, config))
            url <- paste0(base_url, full_endpoint)
            response <- httr::GET(url, headers, timeout(3))
            data <- process_kucoin_response(response, url)
            return(data)
        })
        initial_query <- list(currentPage = 1, pageSize = page_size)
        dt <- await(auto_paginate(
            fetch_page = fetch_page,
            query = initial_query,
            items_field = "items",
            aggregate_fn = function(acc) {
                data.table::rbindlist(acc, fill = TRUE)
            },
            max_pages = max_pages
        ))
        # Convert "createdAt" from milliseconds to POSIXct datetime if the column exists.
        if ("createdAt" %in% colnames(dt)) {
            dt[, createdDatetime := lubridate::as_datetime(createdAt / 1000, origin = "1970-01-01", tz = "UTC")]
        }
        return(dt)
    }, error = function(e) {
        rlang::abort(paste("Error in get_subaccount_list_summary_impl:", conditionMessage(e)))
    })
})

#' Get SubAccount Detail - Balance Implementation
#'
#' This asynchronous function retrieves the balance details for a sub-account specified by its user ID.
#' It sends a GET request to the endpoint `/api/v1/sub-accounts/{subUserId}` with a query parameter
#' `includeBaseAmount` (set to FALSE by default) and processes the returned object. The response contains
#' separate arrays for each account type (mainAccounts, tradeAccounts, marginAccounts, tradeHFAccounts).
#' This function converts each non-empty array to a data.table, adds an "accountType" column, and then
#' combines them. It also adds the subUserId and subName to every row.
#'
#' @param config A list containing API configuration parameters.
#' @param subUserId A string representing the sub-account user ID.
# TODO: confusing name of argument. Should be something like include null values or something.
#' @param includeBaseAmount A boolean indicating whether to include currencies with zero balance (default is FALSE).
#'
#' @return A promise that resolves to a data.table containing the sub-account detail.
#'
#' @examples
#' \dontrun{
#'   dt <- await(get_subaccount_detail_balance_impl(config, "63743f07e0c5230001761d08", includeBaseAmount = FALSE))
#'   print(dt)
#' }
#'
#' @export
get_subaccount_detail_balance_impl <- coro::async(function(config, subUserId, includeBaseAmount = FALSE) {
    tryCatch({
        base_url <- get_base_url(config)
        endpoint <- paste0("/api/v1/sub-accounts/", subUserId)
        query <- list(includeBaseAmount = includeBaseAmount)
        qs <- build_query(query)
        full_endpoint <- paste0(endpoint, qs)
        method <- "GET"
        body <- ""
        headers <- coro::await(build_headers("GET", full_endpoint, body, config))
        url <- paste0(base_url, full_endpoint)
        response <- httr::GET(url, headers, httr::timeout(3))
        data <- process_kucoin_response(response, url)

        # Process each account type into a data.table and add an accountType column.
        result_list <- list()
        if (!is.null(data$mainAccounts) && length(data$mainAccounts) > 0) {
            dt_main <- data.table::as.data.table(data$mainAccounts)
            dt_main[, accountType := "mainAccounts"]
            result_list[[length(result_list) + 1]] <- dt_main
        }
        if (!is.null(data$tradeAccounts) && length(data$tradeAccounts) > 0) {
            dt_trade <- data.table::as.data.table(data$tradeAccounts)
            dt_trade[, accountType := "tradeAccounts"]
            result_list[[length(result_list) + 1]] <- dt_trade
        }
        if (!is.null(data$marginAccounts) && length(data$marginAccounts) > 0) {
            dt_margin <- data.table::as.data.table(data$marginAccounts)
            dt_margin[, accountType := "marginAccounts"]
            result_list[[length(result_list) + 1]] <- dt_margin
        }
        if (!is.null(data$tradeHFAccounts) && length(data$tradeHFAccounts) > 0) {
            dt_tradeHF <- data.table::as.data.table(data$tradeHFAccounts)
            dt_tradeHF[, accountType := "tradeHFAccounts"]
            result_list[[length(result_list) + 1]] <- dt_tradeHF
        }
        if (length(result_list) == 0) {
            dt <- data.table::data.table()
        } else {
            dt <- data.table::rbindlist(result_list, fill = TRUE)
        }
        # Add subUserId and subName from the parent object.
        dt[, subUserId := data$subUserId]
        dt[, subName := data$subName]
        return(dt)
    }, error = function(e) {
        rlang::abort(paste("Error in get_subaccount_detail_balance_impl:", conditionMessage(e)))
    })
})