# File: ./R/impl_spottrading_orders_cancel.R

box::use(
    ./helpers_api[process_kucoin_response, build_headers],
    ./utils[build_query, get_base_url, verify_symbol, get_api_keys],
    coro[async, await],
    data.table[data.table],
    httr[DELETE, timeout],
    rlang[abort]
)

#' Cancel Order By OrderId (Implementation)
#'
#' Cancels a spot order by its order ID on the KuCoin Spot trading system asynchronously.
#' This function sends a cancellation request and returns the order ID if the request is successfully sent.
#' Note that the actual cancellation status must be checked via order status or Websocket subscription.
#' 
#' ### Difference Between Cancel By OrderId and Cancel By ClientOid
#' - **Cancel By OrderId**: Use this when you have the unique order ID generated by KuCoin. This is useful if you are tracking orders using KuCoin's identifiers.
#' - **Cancel By ClientOid**: Use this when you have assigned a unique client order ID (clientOid) to your orders. This is convenient if you are tracking orders using your own identifiers and want to cancel them without mapping to KuCoin's order IDs.
#' 
#' Choose the method that aligns with how you manage and track your orders in your system.
#'
#' ### Workflow Overview
#' 1. **Parameter Validation**: Ensures `orderId` and `symbol` are provided and valid.
#' 2. **Request Construction**: Builds the API endpoint with `orderId` and `symbol` as a query parameter.
#' 3. **Authentication**: Generates headers with API credentials using `build_headers()`.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response and returns the order ID if successful.
#'
#' ### API Endpoint
#' `DELETE https://api.kucoin.com/api/v1/hf/orders/{orderId}?symbol={symbol}`
#'
#' ### Usage
#' Used to cancel a specific spot trading order on KuCoin by its order ID.
#'
#' ### Official Documentation
#' [KuCoin Cancel Order By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-order-by-orderld)
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to cancel. Required.
#' @param symbol Character string; the trading pair symbol (e.g., "BTC-USDT"). Required.
#' @return Promise resolving to a `data.table` containing:
#'   - `orderId` (character): The order ID that was requested to be cancelled.
#' @examples
#' \dontrun{
#' main_async <- coro::async(function() {
#'   # Cancel an order by orderId
#'   result <- await(cancel_order_by_order_id_impl(
#'     orderId = "671124f9365ccb00073debd4",
#'     symbol = "BTC-USDT"
#'   ))
#'   print(result)
#' })
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_order_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId,
    symbol
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }
        if (is.null(symbol) || !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol' must be a valid ticker (e.g., 'BTC-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- paste0("/api/v1/hf/orders/", orderId)
        query_params <- list(symbol = symbol)
        query_string <- build_query(query_params)
        endpoint_with_query <- paste0(endpoint, "?", query_string)
        full_url <- paste0(base_url, endpoint_with_query)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint_with_query, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return result as data.table
        result_dt <- data.table::data.table(orderId = parsed_response$data$orderId)
        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_order_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Cancel Order By ClientOid (Implementation)
#'
#' Cancels a spot order by its client order ID (clientOid) on the KuCoin Spot trading system asynchronously.
#' This function sends a cancellation request and returns the clientOid if the request is successfully sent.
#' Note that the actual cancellation status must be checked via order status or Websocket subscription.
#'
#' ### Difference Between Cancel By OrderId and Cancel By ClientOid
#' - **Cancel By OrderId**: Use this when you have the unique order ID generated by KuCoin. This is useful if you are tracking orders using KuCoin's identifiers.
#' - **Cancel By ClientOid**: Use this when you have assigned a unique client order ID (clientOid) to your orders. This is convenient if you are tracking orders using your own identifiers and want to cancel them without mapping to KuCoin's order IDs.
#' 
#' Choose the method that aligns with how you manage and track your orders in your system.
#'
#' ### Workflow Overview
#' 1. **Parameter Validation**: Ensures `clientOid` and `symbol` are provided and valid.
#' 2. **Request Construction**: Builds the API endpoint with `clientOid` and `symbol` as a query parameter.
#' 3. **Authentication**: Generates headers with API credentials using `build_headers()`.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response and returns the clientOid if successful.
#'
#' ### API Endpoint
#' `DELETE https://api.kucoin.com/api/v1/hf/orders/client-order/{clientOid}?symbol={symbol}`
#'
#' ### Usage
#' Used to cancel a specific spot trading order on KuCoin by its client order ID.
#'
#' ### Official Documentation
#' [KuCoin Cancel Order By ClientOid](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-order-by-clientoid)
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param clientOid Character string; the unique client order ID assigned by the user when placing the order. Required.
#' @param symbol Character string; the trading pair symbol (e.g., "BTC-USDT"). Required.
#' @return Promise resolving to a `data.table` containing:
#'   - `clientOid` (character): The client order ID that was requested to be cancelled.
#' @examples
#' \dontrun{
#' main_async <- coro::async(function() {
#'   # Cancel an order by clientOid
#'   result <- await(cancel_order_by_client_oid_impl(
#'     clientOid = "5c52e11203aa677f33e493fb",
#'     symbol = "BTC-USDT"
#'   ))
#'   print(result)
#' })
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_order_by_client_oid_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    clientOid,
    symbol
) {
    tryCatch({
        # Validate parameters
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) == 0) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string.")
        }
        if (is.null(symbol) || !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol' must be a valid ticker (e.g., 'BTC-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- paste0("/api/v1/hf/orders/client-order/", clientOid)
        query_params <- list(symbol = symbol)
        query_string <- build_query(query_params)
        endpoint_with_query <- paste0(endpoint, "?", query_string)
        full_url <- paste0(base_url, endpoint_with_query)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint_with_query, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return result as data.table
        result_dt <- data.table::data.table(clientOid = parsed_response$data$clientOid)
        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_order_by_client_oid_impl: %s", conditionMessage(e)))
    })
})

#' Cancel Partial Order (Implementation)
#'
#' Cancels a specified quantity of a spot order by its order ID on the KuCoin Spot trading system asynchronously.
#' This function sends a cancellation request for the specified size and returns the order ID and canceled size if the request is successfully sent.
#' Note that the actual cancellation status must be checked via order status or WebSocket subscription.
#'
#' ### Description
#' This endpoint cancels a specified quantity of an existing order based on its `orderId`. Unlike full cancellation endpoints, it allows partial cancellation, leaving the remaining order quantity active. The order execution priority (price first, time first) is not affected by this operation.
#'
#' ### Differences from Other Cancellation Functions
#' - **Cancel Order By OrderId**: Cancels the entire order using the order ID.
#' - **Cancel Order By ClientOid**: Cancels the entire order using the client-assigned ID.
#' - **Cancel Partial Order**: Cancels only a specified quantity of the order, useful for reducing order size without full cancellation.
#'
#' ### Workflow
#' 1. **Parameter Validation**: Ensures `orderId`, `symbol`, and `cancelSize` are non-empty strings, with `symbol` being a valid trading pair.
#' 2. **Request Construction**: Builds the API endpoint with `orderId` in the path and `symbol` and `cancelSize` as query parameters.
#' 3. **Authentication**: Generates headers using API credentials via `build_headers()`.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response and returns the `orderId` and `cancelSize` if successful.
#'
#' ### API Endpoint
#' `DELETE https://api.kucoin.com/api/v1/hf/orders/cancel/{orderId}?symbol={symbol}&cancelSize={cancelSize}`
#'
#' ### Rate Limit
#' - **Weight**: 2 (higher than full cancellation endpoints, which are typically 1).
#'
#' ### Official Documentation
#' [KuCoin Cancel Partial Order](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-partial-order)
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to partially cancel. Required.
#' @param symbol Character string; the trading pair symbol (e.g., "BTC-USDT"). Required.
#' @param cancelSize Character string; the quantity of the order to cancel (e.g., "0.00001"). Required.
#' @return Promise resolving to a `data.table` containing:
#'   - `orderId` (character): The order ID that was partially canceled.
#'   - `cancelSize` (character): The quantity that was canceled.
#' @examples
#' \dontrun{
#' main_async <- coro::async(function() {
#'   # Partially cancel an order
#'   result <- await(cancel_partial_order_impl(
#'     orderId = "6711f73c1ef16c000717bb31",
#'     symbol = "BTC-USDT",
#'     cancelSize = "0.00001"
#'   ))
#'   print(result)
#' })
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_partial_order_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId,
    symbol,
    cancelSize
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }
        if (is.null(symbol) || !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol' must be a valid ticker (e.g., 'BTC-USDT').")
        }
        if (is.null(cancelSize) || !is.character(cancelSize) || nchar(cancelSize) == 0) {
            rlang::abort("Parameter 'cancelSize' must be a non-empty string.")
        }

        # Construct endpoint and query string
        endpoint <- paste0("/api/v1/hf/orders/cancel/", orderId)
        query_params <- list(symbol = symbol, cancelSize = cancelSize)
        query_string <- build_query(query_params)
        endpoint_with_query <- paste0(endpoint, "?", query_string)
        full_url <- paste0(base_url, endpoint_with_query)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint_with_query, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return result as data.table
        result_dt <- data.table::data.table(
            orderId = parsed_response$data$orderId,
            cancelSize = parsed_response$data$cancelSize
        )
        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_partial_order_impl: %s", conditionMessage(e)))
    })
})

#' Cancel All Orders By Symbol (Implementation)
#'
#' Cancels all spot orders for a specified symbol on the KuCoin Spot trading system asynchronously.
#' This endpoint sends a cancellation request for all orders associated with the given symbol and returns a success indicator if the request is accepted.
#' Note that this endpoint only initiates cancellation; the actual status of individual orders must be checked via order status endpoints or WebSocket subscription.
#'
#' @section Description:
#' This function interacts with the KuCoin API endpoint `DELETE /api/v1/hf/orders?symbol={symbol}` to cancel all spot orders for a specific trading pair (e.g., "BTC-USDT").
#' It is useful for quickly canceling multiple orders for a symbol, such as when adjusting trading strategies or managing risk in a specific market.
#'
#' @section Differences from Other Cancellation Endpoints:
#' - **Cancel Order By OrderId**: Targets a single order using its unique order ID.
#' - **Cancel Order By ClientOid**: Targets a single order using a client-assigned ID.
#' - **Cancel Partial Order**: Cancels a portion of a single order.
#' - **Cancel All Orders By Symbol**: Cancels **all** orders for a specified symbol in one request, offering efficiency for bulk cancellations.
#'
#' Use this function when you need to clear all open orders for a trading pair in a single operation.
#'
#' @section Workflow:
#' 1. **Parameter Validation**: Ensures `symbol` is a non-empty string.
#' 2. **Request Construction**: Builds the endpoint URL with `symbol` as a query parameter.
#' 3. **Authentication**: Generates private API headers using the provided `keys`.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response and returns a `data.table` with the result if successful.
#'
#' @section API Details:
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v1/hf/orders?symbol={symbol}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **Official Documentation**: [KuCoin Cancel All Orders By Symbol](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-all-orders-by-symbol)
#'
#' @param keys List; API configuration parameters (e.g., from `get_api_keys()`). Contains API key, secret, and passphrase. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API (e.g., "https://api.kucoin.com"). Defaults to `get_base_url()`.
#' @param symbol Character string; the trading pair symbol (e.g., "BTC-USDT"). Required.
#' @return Promise resolving to a `data.table` with:
#'   - `result` (character): "success" if the cancellation request is accepted.
#' @section Examples:
#' ```r
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Cancel all orders for BTC-USDT
#'   result <- await(cancel_all_orders_by_symbol_impl(sound = "BTC-USDT"))
#'   print(result)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' ```
#' **Expected Output**:
#' ```
#'    result
#' 1: success
#' ```
#'
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_all_orders_by_symbol_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    symbol
) {
    tryCatch({
        # Validate parameters
        if (is.null(symbol) || !is.character(symbol) || nchar(symbol) == 0) {
            rlang::abort("Parameter 'symbol' must be a non-empty string (e.g., 'BTC-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v1/hf/orders"
        query_params <- list(symbol = symbol)
        query_string <- paste0("symbol=", symbol) # Simplified; assumes build_query exists elsewhere
        endpoint_with_query <- paste0(endpoint, "?", query_string)
        full_url <- paste0(base_url, endpoint_with_query)

        # Generate authentication headers (assumes build_headers is defined)
        headers <- await(build_headers("DELETE", endpoint_with_query, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response (assumes process_kucoin_response is defined)
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return result as data.table
        data.table::data.table(result = parsed_response$data)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_all_orders_by_symbol_impl: %s", conditionMessage(e)))
    })
})
