# File: ./R/impl_spottrading_orders_oco.R

box::use(
    ./helpers_api[process_kucoin_response, build_headers],
    ./utils[build_query, get_base_url, verify_symbol, get_api_keys],
    ./utils_time_convert_kucoin[time_convert_from_kucoin],
    coro[async, await],
    data.table[data.table, rbindlist],
    httr[POST, DELETE, GET, timeout, content_type_json],
    jsonlite[toJSON],
    rlang[abort, arg_match0]
)

#' Add OCO Order (Implementation)
#'
#' Places an OCO (One-Cancels-the-Other) order on the KuCoin Spot trading system asynchronously by sending a POST request to the `/api/v3/oco/order` endpoint.
#' An OCO order combines a limit order and a stop-limit order, where executing one cancels the other, returning a `data.table` with the order ID.
#'
#' ## What is an OCO Order?
#' An OCO (One-Cancels-the-Other) order is a sophisticated trading tool that pairs a limit order (to secure profits) with a stop-limit order (to cap losses).
#' When one order executes—either hitting a profit target or a stop-loss threshold—the other is automatically canceled. This is particularly useful for:
#' - **Risk Management**: Set a stop-loss to limit potential losses if the market moves against your position, e.g., buying BTC at $50,000 with a stop at $48,000.
#' - **Profit Taking**: Lock in gains at a target price without constant monitoring, e.g., selling at $55,000 after buying at $50,000.
#' - **Volatile Markets**: Automate trading decisions in fast-moving conditions, reducing emotional bias and ensuring discipline.
#' For example, a trader might place an OCO order to buy BTC at $50,000, setting a limit sell at $55,000 (profit) and a stop-limit sell at $48,000 (loss protection).
#' If BTC reaches $55,000, the profit is secured, and the stop cancels; if it drops to $48,000, losses are limited, and the limit cancels.
#'
#' ## Description
#' This function constructs a JSON request body with required parameters (`symbol`, `side`, `price`, `size`, `clientOid`, `stopPrice`, `limitPrice`)
#' and optional fields (`remark`, `tradeType`), authenticates the request, and processes the response into a `data.table`.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures required fields are non-empty strings and validates `side` and `tradeType` enums.
#' 2. **Request Construction**: Builds a named list of parameters, excluding NULL values, and converts it to JSON using `toJSON`.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the POST method, endpoint, and JSON body.
#' 4. **API Request**: Sends a POST request to the KuCoin API with a 3-second timeout via `httr::POST`.
#' 5. **Response Processing**: Parses the response with `process_kucoin_response`, checks for success ("200000"), and converts the `data` field to a `data.table`.
#'
#' ## API Details
#' - **Endpoint**: `POST https://api.kucoin.com/api/v3/oco/order`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: addOcoOrder
#' - **Official Documentation**: [KuCoin Add OCO Order](https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-oco-order)
#'
#' ## Request
#' ### Body Parameters (application/json)
#' - `symbol`: String (required) - Trading pair symbol (e.g., "BTC-USDT").
#' - `side`: Enum<String> (required) - Order side: "buy" or "sell".
#' - `price`: String (required) - Limit order price.
#' - `size`: String (required) - Order quantity.
#' - `clientOid`: String (required) - Unique client order ID (max 40 characters, alphanumeric, underscores, or hyphens).
#' - `stopPrice`: String (required) - Trigger price for the stop-limit order.
#' - `limitPrice`: String (required) - Limit order price after triggering take-profit or stop-loss.
#' - `remark`: String (optional) - Order remarks (max 20 characters).
#' - `tradeType`: Enum<String> (optional) - Transaction type: "TRADE" (default).
#'
#' ### Example Request
#' ```bash
#' curl --location --request POST 'https://api.kucoin.com/api/v3/oco/order' \
#' --header 'Content-Type: application/json' \
#' --data-raw '{
#'     "symbol": "BTC-USDT",
#'     "side": "buy",
#'     "price": "94000",
#'     "size": "0.1",
#'     "clientOid": "5c52e11203aa67f1e493fb",
#'     "stopPrice": "98000",
#'     "limitPrice": "96000",
#'     "remark": "this is remark",
#'     "tradeType": "TRADE"
#' }'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `orderId`: String (required) - Unique order ID generated by the system.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "orderId": "674c316e688dea0007c7b986"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param symbol Character string; trading pair symbol (e.g., "BTC-USDT"). Required.
#' @param side Character string; order side: "buy" or "sell". Required.
#' @param price Character string; limit order price (e.g., "94000"). Required.
#' @param size Character string; order quantity (e.g., "0.1"). Required.
#' @param clientOid Character string; unique client order ID (max 40 characters, e.g., "5c52e11203aa67f1e493fb"). Required.
#' @param stopPrice Character string; stop-limit trigger price (e.g., "98000"). Required.
#' @param limitPrice Character string; stop-limit order price (e.g., "96000"). Required.
#' @param remark Character string; optional remarks (max 20 characters, e.g., "this is remark").
#' @param tradeType Character string; transaction type: "TRADE" (default).
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `orderId` (character): Unique order ID generated by the KuCoin system for the OCO order.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Place an OCO order for BTC-USDT
#'   oco_order <- await(add_order_oco_impl(
#'     symbol = "BTC-USDT",
#'     side = "buy",
#'     price = "94000",
#'     size = "0.1",
#'     clientOid = "5c52e11203aa67f1e493fb",
#'     stopPrice = "98000",
#'     limitPrice = "96000",
#'     remark = "Profit and Stop"
#'   ))
#'   print(oco_order)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr POST timeout content_type_json
#' @importFrom jsonlite toJSON
#' @importFrom rlang abort arg_match0
#' @export
add_order_oco_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    symbol,
    side,
    price,
    size,
    clientOid,
    stopPrice,
    limitPrice,
    remark = NULL,
    tradeType = "TRADE"
) {
    tryCatch({
        # Validate parameters
        if (is.null(symbol) || !is.character(symbol) || !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol' must be a valid trading pair (e.g., 'BTC-USDT').")
        }
        if (is.null(side) || !is.character(side)) {
            rlang::abort("Parameter 'side' must be 'buy' or 'sell'.")
        }
        side <- rlang::arg_match0(side, c("buy", "sell"), "side")
        if (is.null(price) || !is.character(price) || nchar(price) == 0) {
            rlang::abort("Parameter 'price' must be a non-empty string (e.g., '94000').")
        }
        if (is.null(size) || !is.character(size) || nchar(size) == 0) {
            rlang::abort("Parameter 'size' must be a non-empty string (e.g., '0.1').")
        }
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) > 40) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string with max 40 characters.")
        }
        if (is.null(stopPrice) || !is.character(stopPrice) || nchar(stopPrice) == 0) {
            rlang::abort("Parameter 'stopPrice' must be a non-empty string (e.g., '98000').")
        }
        if (is.null(limitPrice) || !is.character(limitPrice) || nchar(limitPrice) == 0) {
            rlang::abort("Parameter 'limitPrice' must be a non-empty string (e.g., '96000').")
        }
        if (!is.null(remark) && (!is.character(remark) || nchar(remark) > 20)) {
            rlang::abort("Parameter 'remark' must be a string with max 20 characters.")
        }
        if (!is.null(tradeType)) {
            tradeType <- rlang::arg_match0(tradeType, "TRADE", "tradeType")
        }

        # Construct request body
        body_list <- list(
            symbol = symbol,
            side = side,
            price = price,
            size = size,
            clientOid = clientOid,
            stopPrice = stopPrice,
            limitPrice = limitPrice,
            tradeType = tradeType
        )
        if (!is.null(remark)) body_list$remark <- remark
        body_json <- jsonlite::toJSON(body_list, auto_unbox = TRUE)

        # Prepare API request
        endpoint <- "/api/v3/oco/order"
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("POST", endpoint, body_json, keys))

        # Send POST request
        response <- httr::POST(
            url = full_url,
            body = body_json,
            headers,
            httr::content_type_json(),
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return as data.table
        return(data.table::data.table(orderId = parsed_response$data$orderId))
    }, error = function(e) {
        rlang::abort(sprintf("Error in add_order_oco_impl: %s", conditionMessage(e)))
    })
})

#' Cancel OCO Order By OrderId (Implementation)
#'
#' Cancels an existing OCO order on the KuCoin Spot trading system using its system-generated order ID (`orderId`) asynchronously by sending a DELETE request to the `/api/v3/oco/order/{orderId}` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO (One-Cancels-the-Other) order pairs a limit order (profit target) with a stop-limit order (loss limit). Canceling an OCO order removes both components, which is useful when:
#' - **Strategy Adjustment**: Market conditions shift, and you no longer want automated profit-taking or loss-limiting (e.g., news-driven volatility).
#' - **Manual Intervention**: You decide to manage the position manually instead of relying on pre-set triggers.
#' - **Error Correction**: You need to correct an OCO order placed with incorrect parameters.
#' For instance, if you set an OCO to sell BTC at $55,000 (profit) or $48,000 (stop-loss) but BTC’s volatility decreases, you might cancel it to set tighter limits.
#'
#' ## Description
#' This function initiates the cancellation of an OCO order identified by its `orderId`, returning a `data.table` with the IDs of the canceled limit and stop-limit orders.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `orderId` is a non-empty string.
#' 2. **Request Construction**: Constructs the endpoint URL by embedding `orderId` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the DELETE method and endpoint.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout via `httr::DELETE`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and converts the `cancelledOrderIds` array to a `data.table` column as a list.
#'
#' ## API Details
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v3/oco/order/{orderId}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: cancelOcoOrderByOrderId
#' - **Official Documentation**: [KuCoin Cancel OCO Order By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-oco-order-by-orderld)
#'
#' ## Request
#' ### Path Parameters
#' - `orderId`: String (required) - The unique order ID generated by the trading system (e.g., "674c316e688dea0007c7b986").
#'
#' ### Example Request
#' ```bash
#' curl --location --request DELETE 'https://api.kucoin.com/api/v3/oco/order/674c316e688dea0007c7b986'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `cancelledOrderIds`: Array[String] (required) - List of two order IDs related to the canceled OCO order (limit and stop-limit components).
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "cancelledOrderIds": [
#'       "vs93gpqc6kkmkk57003gok16",
#'       "vs93gpqc6kkmkk57003gok17"
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to cancel (e.g., "674c316e688dea0007c7b986"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `cancelledOrderIds` (list): A list of two character strings representing the IDs of the canceled limit and stop-limit orders.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Cancel an OCO order by orderId
#'   canceled_orders <- await(cancel_order_oco_by_order_id_impl(
#'     orderId = "674c316e688dea0007c7b986"
#'   ))
#'   print(canceled_orders)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_order_oco_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v3/oco/order/", orderId)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return as data.table
        return(data.table::data.table(cancelledOrderIds = list(parsed_response$data$cancelledOrderIds)))
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_order_oco_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Cancel OCO Order By ClientOid (Implementation)
#'
#' Cancels an existing OCO order on the KuCoin Spot trading system using its client-assigned order ID (`clientOid`) asynchronously by sending a DELETE request to the `/api/v3/oco/client-order/{clientOid}` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO (One-Cancels-the-Other) order links a limit order (profit target) with a stop-limit order (loss limit). Canceling by `clientOid` allows:
#' - **Custom Tracking**: Use your unique ID to cancel without needing the system `orderId`, ideal for systems tracking orders locally.
#' - **Flexibility**: Adjust strategies when market trends shift unexpectedly (e.g., canceling an OCO if a breakout is anticipated).
#' - **Error Handling**: Quickly remove an OCO order if set incorrectly, such as wrong price levels.
#' For example, if an OCO order was placed with a `clientOid` to sell BTC at $55,000 or $48,000 but you detect a potential rally, you might cancel it using your custom ID.
#'
#' ## Description
#' This function initiates the cancellation of an OCO order identified by its `clientOid`, returning a `data.table` with the IDs of the canceled limit and stop-limit orders.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `clientOid` is a non-empty string.
#' 2. **Request Construction**: Constructs the endpoint URL by embedding `clientOid` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the DELETE method and endpoint.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout via `httr::DELETE`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and converts the `cancelledOrderIds` array to a `data.table` column as a list.
#'
#' ## API Details
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v3/oco/client-order/{clientOid}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: cancelOcoOrderByClientOid
#' - **Official Documentation**: [KuCoin Cancel OCO Order By ClientOid](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-oco-order-by-clientoid)
#'
#' ## Request
#' ### Path Parameters
#' - `clientOid`: String (required) - Unique client order ID created by the user (e.g., "5c52e11203aa67f1e493fb").
#'
#' ### Example Request
#' ```bash
#' curl --location --request DELETE 'https://api.kucoin.com/api/v3/oco/client-order/5c52e11203aa67f1e493fb'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `cancelledOrderIds`: Array[String] (required) - List of two order IDs related to the canceled OCO order (limit and stop-limit components).
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "cancelledOrderIds": [
#'       "vs93gpqc6r0mkk57003gok3h",
#'       "vs93gpqc6r0mkk57003gok3i"
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param clientOid Character string; the unique client order ID to cancel (e.g., "5c52e11203aa67f1e493fb"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `cancelledOrderIds` (list): A list of two character strings representing the IDs of the canceled limit and stop-limit orders.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Cancel an OCO order by clientOid
#'   canceled_orders <- await(cancel_order_oco_by_client_oid_impl(
#'     clientOid = "5c52e11203aa67f1e493fb"
#'   ))
#'   print(canceled_orders)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_order_oco_by_client_oid_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    clientOid
) {
    tryCatch({
        # Validate parameters
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) == 0) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v3/oco/client-order/", clientOid)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return as data.table
        return(data.table::data.table(cancelledOrderIds = list(parsed_response$data$cancelledOrderIds)))
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_order_oco_by_client_oid_impl: %s", conditionMessage(e)))
    })
})

#' Get OCO Order By OrderId (Implementation)
#'
#' Retrieves basic information about an OCO order using its system-generated order ID (`orderId`) from the KuCoin Spot trading system asynchronously by sending a GET request to the `/api/v3/oco/order/{orderId}` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO order combines a limit order (e.g., to take profits) with a stop-limit order (e.g., to limit losses), canceling one when the other executes. Retrieving this info is useful for:
#' - **Status Monitoring**: Check if the order is "NEW", "TRIGGERED", or "CANCELED" to assess its current state.
#' - **Trade Review**: Confirm order details like symbol and placement time match your strategy.
#' - **Decision Making**: Use status to decide whether to adjust or cancel (e.g., if still "NEW" during a trend shift).
#' For example, checking an OCO order placed at $50,000 for BTC might show it’s still "NEW", prompting a tighter stop if volatility rises.
#'
#' ## Description
#' This function fetches basic OCO order details (`orderId`, `symbol`, `clientOid`, `orderTime`, `status`) and returns them in a `data.table`.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `orderId` is a non-empty string.
#' 2. **Request Construction**: Constructs the endpoint URL by embedding `orderId` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout via `httr::GET`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and converts the `data` object to a `data.table`.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v3/oco/order/{orderId}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getOcoOrderByOrderId
#' - **Official Documentation**: [KuCoin Get OCO Order By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-by-orderld)
#'
#' ## Request
#' ### Path Parameters
#' - `orderId`: String (required) - The unique order ID generated by the trading system (e.g., "674c3b6e688dea0007c7bab2").
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v3/oco/order/674c3b6e688dea0007c7bab2'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `symbol`: String (required) - Trading pair symbol.
#'   - `clientOid`: String (required) - Client-assigned order ID.
#'   - `orderId`: String (required) - System-generated order ID.
#'   - `orderTime`: Integer<int64> (required) - Order placement time in milliseconds.
#'   - `status`: Enum<String> (required) - Order status: "NEW", "DONE", "TRIGGERED", "CANCELED".
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "orderId": "674c3b6e688dea0007c7bab2",
#'     "symbol": "BTC-USDT",
#'     "clientOid": "5c52e1203aa6f37f1e493fb",
#'     "orderTime": 1733049198863,
#'     "status": "NEW"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to retrieve (e.g., "674c3b6e688dea0007c7bab2"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `orderId` (character): Unique order ID generated by the KuCoin system.
#'   - `symbol` (character): Trading pair symbol (e.g., "BTC-USDT").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `orderTime` (integer): Order placement time in milliseconds.
#'   - `status` (character): Order status ("NEW", "DONE", "TRIGGERED", "CANCELED").
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve OCO order by orderId
#'   oco_order <- await(get_order_oco_by_order_id_impl(
#'     orderId = "674c3b6e688dea0007c7bab2"
#'   ))
#'   print(oco_order)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_order_oco_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v3/oco/order/", orderId)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("GET", endpoint, NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        return(data.table::rbindlist(list(parsed_response$data), fill = TRUE))
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_order_oco_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Get OCO Order By ClientOid (Implementation)
#'
#' Retrieves basic information about an OCO order using its client-assigned order ID (`clientOid`) from the KuCoin Spot trading system asynchronously by sending a GET request to the `/api/v3/oco/client-order/{clientOid}` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO order pairs a limit order (profit target) with a stop-limit order (loss limit), canceling one when the other executes. Fetching by `clientOid` is useful for:
#' - **Custom Tracking**: Monitor orders using your own ID system without relying on KuCoin’s `orderId`.
#' - **Status Checks**: Verify if an order is still active ("NEW") or has executed ("TRIGGERED"/"DONE").
#' - **Strategy Sync**: Ensure your trading system’s records align with KuCoin’s state (e.g., after a network delay).
#' For instance, retrieving an OCO order with a `clientOid` might confirm it’s "NEW", allowing you to adjust if market conditions change.
#'
#' ## Description
#' This function fetches basic OCO order details (`orderId`, `symbol`, `clientOid`, `orderTime`, `status`) and returns them in a `data.table`.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `clientOid` is a non-empty string.
#' 2. **Request Construction**: Constructs the endpoint URL by embedding `clientOid` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout via `httr::GET`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and converts the `data` object to a `data.table`.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v3/oco/client-order/{clientOid}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getOcoOrderByClientOid
#' - **Official Documentation**: [KuCoin Get OCO Order By ClientOid](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-by-clientoid)
#'
#' ## Request
#' ### Path Parameters
#' - `clientOid`: String (required) - Unique client order ID created by the user (e.g., "5c52e1203aa6f3g7f1e493fb").
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v3/oco/client-order/5c52e1203aa6f3g7f1e493fb'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `symbol`: String (required) - Trading pair symbol.
#'   - `clientOid`: String (required) - Client-assigned order ID.
#'   - `orderId`: String (required) - System-generated order ID.
#'   - `orderTime`: Integer<int64> (required) - Order placement time in milliseconds.
#'   - `status`: String (required) - Order status: "NEW", "DONE", "TRIGGERED", "CANCELED".
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "orderId": "674c3cfa72cf2800072ee7ce",
#'     "symbol": "BTC-USDT",
#'     "clientOid": "5c52e1203aa6f3g7f1e493fb",
#'     "orderTime": 1733049594803,
#'     "status": "NEW"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param clientOid Character string; the unique client order ID to retrieve (e.g., "5c52e1203aa6f3g7f1e493fb"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `orderId` (character): Unique order ID generated by the KuCoin system.
#'   - `symbol` (character): Trading pair symbol (e.g., "BTC-USDT").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `orderTime` (integer): Order placement time in milliseconds.
#'   - `status` (character): Order status ("NEW", "DONE", "TRIGGERED", "CANCELED").
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve OCO order by clientOid
#'   oco_order <- await(get_order_oco_by_client_oid_impl(
#'     clientOid = "5c52e1203aa6f3g7f1e493fb"
#'   ))
#'   print(oco_order)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_order_oco_by_client_oid_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    clientOid
) {
    tryCatch({
        # Validate parameters
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) == 0) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v3/oco/client-order/", clientOid)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("GET", endpoint, NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        return(data.table::rbindlist(list(parsed_response$data), fill = TRUE))
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_order_oco_by_client_oid_impl: %s", conditionMessage(e)))
    })
})

#' Get OCO Order Detail By OrderId (Implementation)
#'
#' Retrieves detailed information about an OCO order, including its associated limit and stop-limit orders, using its system-generated order ID (`orderId`) from the KuCoin Spot trading system asynchronously by sending a GET request to the `/api/v3/oco/order/details/{orderId}` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO order links a limit order (e.g., profit target) with a stop-limit order (e.g., loss limit), canceling one when the other executes. Fetching detailed info is useful for:
#' - **Execution Analysis**: Review the specific prices and sizes of both orders to evaluate strategy effectiveness.
#' - **Debugging**: Confirm the stop and limit prices align with your intended trade plan (e.g., catching setup errors).
#' - **Performance Tracking**: Assess whether triggers are nearing execution in volatile conditions.
#' For example, detailed info on an OCO order at $50,000 for BTC might show a limit at $55,000 and a stop at $48,000, helping you adjust if the range is too wide.
#'
#' ## Description
#' This function fetches detailed OCO order information (`orderId`, `symbol`, `clientOid`, `orderTime`, `status`, and `orders` array) and returns it in a `data.table` with nested order details as a list column.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `orderId` is a non-empty string.
#' 2. **Request Construction**: Constructs the endpoint URL by embedding `orderId` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout via `httr::GET`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and constructs a `data.table` with `orders` as a list column.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v3/oco/order/details/{orderId}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getOcoOrderDetailByOrderId
#' - **Official Documentation**: [KuCoin Get OCO Order Detail By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-detail-by-orderld)
#'
#' ## Request
#' ### Path Parameters
#' - `orderId`: String (required) - The unique order ID generated by the trading system (e.g., "674c3b6e688dea0007c7bab2").
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v3/oco/order/details/674c3b6e688dea0007c7bab2'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `orderId`: String (required) - System-generated order ID.
#'   - `symbol`: String (required) - Trading pair symbol.
#'   - `clientOid`: String (required) - Client-assigned order ID.
#'   - `orderTime`: Integer<int64> (required) - Order placement time in milliseconds.
#'   - `status`: String (required) - Order status: "NEW", "DONE", "TRIGGERED", "CANCELED".
#'   - `orders`: Array[Object] (required) - List of associated orders (limit and stop-limit), each with:
#'     - `id`: String - Individual order ID.
#'     - `symbol`: String - Trading pair symbol.
#'     - `side`: String - Order side ("buy" or "sell").
#'     - `price`: String - Order price.
#'     - `stopPrice`: String - Trigger price.
#'     - `size`: String - Order quantity.
#'     - `status`: String - Order status.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "orderId": "674c3b6e688dea0007c7bab2",
#'     "symbol": "BTC-USDT",
#'     "clientOid": "5c52e1203aa6f37f1e493fb",
#'     "orderTime": 1733049198863,
#'     "status": "NEW",
#'     "orders": [
#'       {
#'         "id": "vs93gpqc7dn6h3fa003sfelj",
#'         "symbol": "BTC-USDT",
#'         "side": "buy",
#'         "price": "94000.00000000000000000000",
#'         "stopPrice": "94000.00000000000000000000",
#'         "size": "0.10000000000000000000",
#'         "status": "NEW"
#'       },
#'       {
#'         "id": "vs93gpqc7dn6h3fa003sfelk",
#'         "symbol": "BTC-USDT",
#'         "side": "buy",
#'         "price": "96000.00000000000000000000",
#'         "stopPrice": "98000.00000000000000000000",
#'         "size": "0.10000000000000000000",
#'         "status": "NEW"
#'       }
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to retrieve (e.g., "674c3b6e688dea0007c7bab2"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `orderId` (character): Unique order ID generated by the KuCoin system.
#'   - `symbol` (character): Trading pair symbol (e.g., "BTC-USDT").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `orderTime` (integer): Order placement time in milliseconds.
#'   - `status` (character): Order status ("NEW", "DONE", "TRIGGERED", "CANCELED").
#'   - `orders` (list): List of nested objects, each containing:
#'     - `id` (character): Individual order ID.
#'     - `symbol` (character): Trading pair symbol.
#'     - `side` (character): Order side ("buy" or "sell").
#'     - `price` (character): Order price.
#'     - `stopPrice` (character): Trigger price.
#'     - `size` (character): Order quantity.
#'     - `status` (character): Order status ("NEW", etc.).
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve detailed OCO order by orderId
#'   oco_detail <- await(get_order_oco_detail_by_order_id_impl(
#'     orderId = "674c3b6e688dea0007c7bab2"
#'   ))
#'   print(oco_detail)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_order_oco_detail_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v3/oco/order/details/", orderId)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("GET", endpoint, NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table with nested orders as a list
        return(data.table::data.table(
            orderId = parsed_response$data$orderId,
            symbol = parsed_response$data$symbol,
            clientOid = parsed_response$data$clientOid,
            orderTime = parsed_response$data$orderTime,
            status = parsed_response$data$status,
            orders = list(parsed_response$data$orders)
        ))
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_order_oco_detail_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Get OCO Order List (Implementation)
#'
#' Retrieves a paginated list of current OCO orders from the KuCoin Spot trading system asynchronously by sending a GET request to the `/api/v3/oco/orders` endpoint.
#'
#' ## What is an OCO Order?
#' An OCO order combines a limit order (profit target) with a stop-limit order (loss limit), canceling one when the other executes. Listing all OCO orders is useful for:
#' - **Portfolio Oversight**: Review all active OCO strategies across trading pairs to ensure alignment with market conditions.
#' - **Bulk Management**: Identify orders to adjust or cancel based on status (e.g., canceling "NEW" orders if a trend reverses).
#' - **Historical Insight**: Filter by time to analyze past OCO performance for strategy refinement.
#' For example, listing OCO orders might show multiple BTC-USDT pairs with varying profit/loss levels, helping you optimize risk across your portfolio.
#'
#' ## Description
#' This function fetches a list of OCO orders with optional filters (`symbol`, `startAt`, etc.), sorted by latest first, and returns them in a `data.table`.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `query` is a named list and validates `symbol` if provided.
#' 2. **Request Construction**: Constructs the endpoint URL with query parameters from `build_query`.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout via `httr::GET`.
#' 5. **Response Processing**: Parses the response, confirms success ("200000"), and converts the `items` array to a `data.table`, returning an empty structured table if no items exist.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v3/oco/orders`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 2
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getOcoOrderList
#' 
#' - **Official Documentation**: [KuCoin Get OCO Order List](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-oco-order-list)
#'
#' ## Request
#' ### Query Parameters
#' - `symbol`: String (optional) - Filter by trading pair symbol (e.g., "BTC-USDT").
#' - `startAt`: Integer<int64> (optional) - Start time in milliseconds.
#' - `endAt`: Integer<int64> (optional) - End time in milliseconds.
#' - `orderIds`: String (optional) - Comma-separated list of order IDs (up to 500).
#' - `pageSize`: Integer (optional) - Results per page (10–500, default 50).
#' - `currentPage`: Integer (optional) - Page number (minimum 1, default 1).
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v3/oco/orders?symbol=BTC-USDT&pageSize=10&currentPage=1'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `currentPage`: Integer (required) - Current page number.
#'   - `pageSize`: Integer (required) - Number of items per page.
#'   - `totalNum`: Integer (required) - Total number of OCO orders.
#'   - `totalPage`: Integer (required) - Total number of pages.
#'   - `items`: Array[Object] (required) - List of OCO orders, each with:
#'     - `orderId`: String (required) - System-generated order ID.
#'     - `symbol`: String (required) - Trading pair symbol.
#'     - `clientOid`: String (required) - Client-assigned order ID.
#'     - `orderTime`: Integer<int64> (required) - Order placement time in milliseconds.
#'     - `status`: Enum<String> (required) - Order status: "NEW", "DONE", "TRIGGERED", "CANCELED".
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "currentPage": 1,
#'     "pageSize": 50,
#'     "totalNum": 1,
#'     "totalPage": 1,
#'     "items": [
#'       {
#'         "orderId": "674c3cfa72cf2800072ee7ce",
#'         "symbol": "BTC-USDT",
#'         "clientOid": "5c52e1203aa6f3g7f1e493fb",
#'         "orderTime": 1733049594803,
#'         "status": "NEW"
#'       }
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param query Named list; optional query parameters for filtering and pagination (e.g., `list(symbol = "BTC-USDT", pageSize = 10)`).
#' @return Promise resolving to a `data.table` containing:
#'   - `orderId` (character): Unique order ID generated by the KuCoin system.
#'   - `symbol` (character): Trading pair symbol (e.g., "BTC-USDT").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `orderTime` (integer): Order placement time in milliseconds.
#'   - `status` (character): Order status ("NEW", "DONE", "TRIGGERED", "CANCELED").
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve OCO order list with filter
#'   oco_list <- await(get_order_oco_list_impl(
#'     query = list(symbol = "BTC-USDT", pageSize = 10, currentPage = 1)
#'   ))
#'   print(oco_list)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_order_oco_list_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    query = list()
) {
    tryCatch({
        # Validate parameters
        if (!is.list(query)) {
            rlang::abort("Parameter 'query' must be a named list.")
        }
        if ("symbol" %in% names(query) && !is.null(query$symbol) && !verify_symbol(query$symbol)) {
            rlang::abort("Parameter 'query$symbol', if provided, must be a valid trading pair (e.g., 'BTC-USDT').")
        }
        if ("pageSize" %in% names(query) && (!is.integer(query$pageSize) || query$pageSize < 10 || query$pageSize > 500)) {
            rlang::abort("Parameter 'query$pageSize' must be an integer between 10 and 500.")
        }
        if ("currentPage" %in% names(query) && (!is.integer(query$currentPage) || query$currentPage < 1)) {
            rlang::abort("Parameter 'query$currentPage' must be an integer >= 1.")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v3/oco/orders"
        query_string <- build_query(query)
        full_url <- paste0(base_url, endpoint, query_string)

        # Generate authentication headers
        headers <- await(build_headers("GET", paste0(endpoint, query_string), NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        if (length(parsed_response$data$items) == 0) {
            return(data.table::data.table(
                orderId = character(),
                symbol = character(),
                clientOid = character(),
                orderTime = integer(),
                status = character()
            ))
        } else {
            return(data.table::rbindlist(parsed_response$data$items, fill = TRUE))
        }
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_order_oco_list_impl: %s", conditionMessage(e)))
    })
})
