# File: ./R/impl_spottrading_orders_stop.R

box::use(
    ./helpers_api[process_kucoin_response, build_headers],
    ./utils[build_query, get_base_url, verify_symbol, get_api_keys],
    ./utils_time_convert_kucoin[time_convert_from_kucoin],
    coro[async, await],
    data.table[data.table, rbindlist],
    httr[GET, DELETE, POST, timeout, content_type_json],
    jsonlite[toJSON],
    rlang[abort, arg_match0]
)

#' Add Stop Order (Implementation)
#'
#' Places a stop order (limit or market) on the KuCoin Spot trading system asynchronously.
#' This function constructs a JSON request body, sends it to the KuCoin API, and returns a `data.table`
#' containing the resulting order ID and client order ID.
#'
#' ## Description
#' This endpoint allows users to place a stop order on the KuCoin Spot trading system, which triggers when the market price reaches the specified `stopPrice`. Two types of stop orders are supported:
#' - **Limit Stop Order**: Executes at a specified `price` once triggered, requiring both `price` and `size`.
#' - **Market Stop Order**: Executes as a market order once triggered, requiring either `size` or `funds`.
#'
#' The maximum number of untriggered stop orders per trading pair in one account is 20. The function validates parameters based on the order type and ensures compliance with KuCoin API constraints.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures required fields (`type`, `symbol`, `side`, `stopPrice`) are valid, and type-specific fields (`price`, `size`, `funds`) meet requirements.
#' 2. **Request Construction**: Builds a JSON body with required and optional parameters.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the POST method, endpoint, and request body.
#' 4. **API Request**: Sends a POST request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, validates success, and returns a `data.table` with `orderId` and `clientOid`.
#'
#' ## API Details
#' - **Endpoint**: `POST https://api.kucoin.com/api/v1/stop-order`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 1
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: addStopOrder
#' - **Official Documentation**: [KuCoin Add Stop Order](https://www.kucoin.com/docs-new/rest/spot-trading/orders/add-stop-order)
#'
#' ## Request
#' ### Body Parameters (application/json)
#' - `type`: Enum<String> (required) - Order type: "limit" or "market".
#' - `symbol`: String (required) - Trading pair symbol (e.g., "BTC-USDT").
#' - `side`: Enum<String> (required) - Order side: "buy" or "sell".
#' - `clientOid`: String (optional) - Unique client order ID (max 40 characters, alphanumeric, underscores, or hyphens).
#' - `price`: String (optional) - Order price (required for limit orders).
#' - `size`: String (optional) - Order quantity (required for limit orders, optional for market orders if `funds` not provided).
#' - `funds`: String (optional) - Funds for market orders (optional if `size` provided).
#' - `stp`: Enum<String> (optional) - Self Trade Prevention: "DC", "CO", "CN", "CB".
#' - `stopPrice`: String (required) - Trigger price for the stop order.
#' - `remark`: String (optional) - Order remarks (max 20 characters).
#' - `timeInForce`: Enum<String> (optional) - Time in force: "GTC", "GTT", "IOC", "FOK" (required for limit orders).
#' - `cancelAfter`: Integer<int64> (optional) - Cancel after n seconds (for GTT).
#' - `postOnly`: Boolean (optional) - Post-only flag.
#' - `hidden`: Boolean (optional) - Hidden order flag.
#' - `iceberg`: Boolean (optional) - Iceberg order flag.
#' - `visibleSize`: String (optional) - Visible size for iceberg orders.
#' - `tradeType`: String (optional) - Trade type (default "TRADE").
#'
#' ### Example Request
#' ```bash
#' curl --location --request POST 'https://api.kucoin.com/api/v1/stop-order' \
#' --header 'Content-Type: application/json' \
#' --data-raw '{
#'     "type": "limit",
#'     "symbol": "BTC-USDT",
#'     "side": "buy",
#'     "price": "50000",
#'     "size": "0.00001",
#'     "stopPrice": "49000",
#'     "clientOid": "5c52e11203aa677f33e493fb",
#'     "remark": "order remarks"
#' }'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `orderId`: String (required) - Unique order ID generated by the system.
#'   - `clientOid`: String (required) - Client-assigned order ID from the request.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "orderId": "670fd33bf9406e0007ab3945",
#'     "clientOid": "5c52e11203aa677f33e493fb"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param type Character string; order type: "limit" or "market". Required.
#' @param symbol Character string; trading pair symbol (e.g., "BTC-USDT"). Required.
#' @param side Character string; order side: "buy" or "sell". Required.
#' @param stopPrice Character string; trigger price for the stop order. Required.
#' @param clientOid Character string; unique client order ID (max 40 characters). Optional.
#' @param price Character string; price for limit orders. Required for limit orders.
#' @param size Character string; quantity for the order. Required for limit orders, optional for market orders.
#' @param funds Character string; funds for market orders. Optional for market orders.
#' @param stp Character string; self-trade prevention: "DC", "CO", "CN", "CB". Optional.
#' @param remark Character string; order remarks (max 20 characters). Optional.
#' @param timeInForce Character string; time in force: "GTC", "GTT", "IOC", "FOK". Optional, defaults to "GTC".
#' @param cancelAfter Integer; cancel after n seconds for GTT. Optional.
#' @param postOnly Logical; post-only flag. Optional, defaults to `FALSE`.
#' @param hidden Logical; hidden order flag. Optional, defaults to `FALSE`.
#' @param iceberg Logical; iceberg order flag. Optional, defaults to `FALSE`.
#' @param visibleSize Character string; visible size for iceberg orders. Optional.
#' @param tradeType Character string; trade type (e.g., "TRADE"). Optional, defaults to "TRADE".
#' @return Promise resolving to a `data.table` with:
#'   - `orderId` (character): Unique order ID generated by the system.
#'   - `clientOid` (character): Client-assigned order ID.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Place a limit stop order
#'   result <- await(add_stop_order_impl(
#'     type = "limit",
#'     symbol = "BTC-USDT",
#'     side = "buy",
#'     stopPrice = "49000",
#'     price = "50000",
#'     size = "0.00001",
#'     clientOid = "5c52e11203aa677f33e493fb",
#'     remark = "order remarks"
#'   ))
#'   print(result)
#'
#'   # Place a market stop order with size
#'   result <- await(add_stop_order_impl(
#'     type = "market",
#'     symbol = "BTC-USDT",
#'     side = "buy",
#'     stopPrice = "49000",
#'     size = "0.00001",
#'     clientOid = "5c52e11203aa677f33e493fc"
#'   ))
#'   print(result)
#'
#'   # Place a market stop order with funds
#'   result <- await(add_stop_order_impl(
#'     type = "market",
#'     symbol = "BTC-USDT",
#'     side = "buy",
#'     stopPrice = "49000",
#'     funds = "1",
#'     clientOid = "5c52e11203aa677f33e493fd"
#'   ))
#'   print(result)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr POST timeout content_type_json
#' @importFrom jsonlite toJSON
#' @importFrom rlang abort arg_match0
#' @export
add_stop_order_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    type,
    symbol,
    side,
    stopPrice,
    clientOid = NULL,
    price = NULL,
    size = NULL,
    funds = NULL,
    stp = NULL,
    remark = NULL,
    timeInForce = NULL,
    cancelAfter = NULL,
    postOnly = NULL,
    hidden = NULL,
    iceberg = NULL,
    visibleSize = NULL,
    tradeType = "TRADE"
) {
    tryCatch({
        # Validate required parameters
        if (is.null(type) || !is.character(type)) {
            rlang::abort("Parameter 'type' must be a non-empty string: 'limit' or 'market'.")
        }
        type <- rlang::arg_match0(type, c("limit", "market"), "type")

        if (is.null(symbol) || !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol' must be a valid trading pair (e.g., 'BTC-USDT').")
        }

        if (is.null(side) || !is.character(side)) {
            rlang::abort("Parameter 'side' must be a non-empty string: 'buy' or 'sell'.")
        }
        side <- rlang::arg_match0(side, c("buy", "sell"), "side")

        if (is.null(stopPrice) || !is.character(stopPrice) || nchar(stopPrice) == 0) {
            rlang::abort("Parameter 'stopPrice' must be a non-empty string representing the trigger price.")
        }

        # Type-specific validation
        if (type == "limit") {
            if (is.null(price) || !is.character(price) || nchar(price) == 0) {
                rlang::abort("Parameter 'price' is required for limit orders and must be a non-empty string.")
            }
            if (is.null(size) || !is.character(size) || nchar(size) == 0) {
                rlang::abort("Parameter 'size' is required for limit orders and must be a non-empty string.")
            }
            if (!is.null(funds)) {
                rlang::abort("Parameter 'funds' cannot be specified for limit orders.")
            }
        } else if (type == "market") {
            if (!is.null(price)) {
                rlang::abort("Parameter 'price' cannot be specified for market orders.")
            }
            if (is.null(size) && is.null(funds)) {
                rlang::abort("For market orders, either 'size' or 'funds' must be specified.")
            }
            if (!is.null(size) && !is.null(funds)) {
                rlang::abort("For market orders, 'size' and 'funds' cannot both be specified.")
            }
            if (!is.null(size) && (!is.character(size) || nchar(size) == 0)) {
                rlang::abort("Parameter 'size' must be a non-empty string when provided for market orders.")
            }
            if (!is.null(funds) && (!is.character(funds) || nchar(funds) == 0)) {
                rlang::abort("Parameter 'funds' must be a non-empty string when provided for market orders.")
            }
        }

        # Optional parameter validation
        if (!is.null(clientOid) && (!is.character(clientOid) || nchar(clientOid) > 40)) {
            rlang::abort("Parameter 'clientOid' must be a string with a maximum length of 40 characters.")
        }
        if (!is.null(remark) && (!is.character(remark) || nchar(remark) > 20)) {
            rlang::abort("Parameter 'remark' must be a string with a maximum length of 20 characters.")
        }
        if (!is.null(stp)) {
            stp <- rlang::arg_match0(stp, c("DC", "CO", "CN", "CB"), "stp")
        }
        if (!is.null(timeInForce)) {
            timeInForce <- rlang::arg_match0(timeInForce, c("GTC", "GTT", "IOC", "FOK"), "timeInForce")
        }

        # Construct request body
        body_list <- list(
            type = type,
            symbol = symbol,
            side = side,
            stopPrice = stopPrice,
            tradeType = tradeType
        )
        if (!is.null(clientOid)) body_list$clientOid <- clientOid
        if (!is.null(price)) body_list$price <- price
        if (!is.null(size)) body_list$size <- size
        if (!is.null(funds)) body_list$funds <- funds
        if (!is.null(stp)) body_list$stp <- stp
        if (!is.null(remark)) body_list$remark <- remark
        if (!is.null(timeInForce)) body_list$timeInForce <- timeInForce
        if (!is.null(cancelAfter)) body_list$cancelAfter <- as.integer(cancelAfter)
        if (!is.null(postOnly)) body_list$postOnly <- postOnly
        if (!is.null(hidden)) body_list$hidden <- hidden
        if (!is.null(iceberg)) body_list$iceberg <- iceberg
        if (!is.null(visibleSize)) body_list$visibleSize <- visibleSize

        body_json <- jsonlite::toJSON(body_list, auto_unbox = TRUE)

        # Prepare API request
        endpoint <- "/api/v1/stop-order"
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("POST", endpoint, body_json, keys))

        # Send POST request
        response <- httr::POST(
            url = full_url,
            body = body_json,
            headers,
            httr::content_type_json(),
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return as data.table
        result_dt <- data.table::data.table(
            orderId = parsed_response$data$orderId,
            clientOid = parsed_response$data$clientOid
        )
        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in add_stop_order_impl: %s", conditionMessage(e)))
    })
})

#' Cancel Stop Order By ClientOid (Implementation)
#'
#' Cancels a stop order on the KuCoin Spot trading system using its client order ID (`clientOid`) asynchronously.
#' This function sends a cancellation request and returns a `data.table` with the cancelled order's details.
#' Note that this endpoint only initiates cancellation; the actual status must be verified via order status checks or WebSocket subscription.
#'
#' ## Description
#' This endpoint allows users to cancel a stop order identified by its `clientOid`, a user-assigned unique identifier.
#' Stop orders are conditional orders that trigger when the market price reaches a specified `stopPrice`. The function
#' sends a DELETE request to the KuCoin API and returns confirmation details upon successful initiation of the cancellation.
#' The maximum number of untriggered stop orders per trading pair is 20, and this endpoint helps manage that limit by
#' removing specific orders.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `clientOid` is a non-empty string and, if provided, `symbol` is a valid trading pair.
#' 2. **Request Construction**: Builds the endpoint URL with query parameters `symbol` (optional) and `clientOid` (required).
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the DELETE method and endpoint.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, validates success, and returns a `data.table` with `cancelledOrderId` and `clientOid`.
#'
#' ## API Details
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v1/stop-order/cancelOrderByClientOid`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 5
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: cancelStopOrderByClientOid
#' - **Official Documentation**: [KuCoin Cancel Stop Order By ClientOid](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-stop-order-by-clientoid)
#'
#' ## Request
#' ### Query Parameters
#' - `symbol`: String (optional) - The trading pair symbol (e.g., "BTC-USDT").
#' - `clientOid`: String (required) - Unique client order ID created by the user (e.g., "689ff597f4414061aa819cc414836abd").
#'
#' ### Example Request
#' ```bash
#' curl --location --request DELETE 'https://api.kucoin.com/api/v1/stop-order/cancelOrderByClientOid?symbol=BTC-USDT&clientOid=689ff597f4414061aa819cc414836abd'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `clientOid`: String (required) - Client-assigned order ID from the request.
#'   - `cancelledOrderId`: String (required) - Unique ID of the cancelled order assigned by the system.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "cancelledOrderId": "vs8hoo8ksc8mario0035a74n",
#'     "clientOid": "689ff597f4414061aa819cc414836abd"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param symbol Character string; the trading pair symbol (e.g., "BTC-USDT"). Optional.
#' @param clientOid Character string; the unique client order ID to cancel (e.g., "689ff597f4414061aa819cc414836abd"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `cancelledOrderId` (character): Unique ID of the cancelled order.
#'   - `clientOid` (character): Client-assigned order ID.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Cancel a stop order by clientOid
#'   cancellation <- await(cancel_stop_order_by_client_oid_impl(
#'     symbol = "BTC-USDT",
#'     clientOid = "689ff597f4414061aa819cc414836abd"
#'   ))
#'   print(cancellation)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#'
#' # Expected Output:
#' #    cancelledOrderId         clientOid
#' # 1: vs8hoo8ksc8mario0035a74n 689ff597f4414061aa819cc414836abd
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_stop_order_by_client_oid_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    symbol = NULL,
    clientOid
) {
    tryCatch({
        # Validate parameters
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) == 0) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string.")
        }
        if (!is.null(symbol) && !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol', if provided, must be a valid ticker (e.g., 'BTC-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v1/stop-order/cancelOrderByClientOid"
        query_params <- list(clientOid = clientOid)
        if (!is.null(symbol)) query_params$symbol <- symbol
        query_string <- build_query(query_params)
        endpoint_with_query <- paste0(endpoint, query_string)
        full_url <- paste0(base_url, endpoint_with_query)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint_with_query, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        result_dt <- data.table::data.table(
            cancelledOrderId = parsed_response$data$cancelledOrderId,
            clientOid = parsed_response$data$clientOid
        )

        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_stop_order_by_client_oid_impl: %s", conditionMessage(e)))
    })
})

#' Cancel Stop Order By OrderId (Implementation)
#'
#' Cancels a stop order on the KuCoin Spot trading system using its system-generated order ID (`orderId`) asynchronously.
#' This function sends a cancellation request and returns a `data.table` with the cancelled order's details.
#' Note that this endpoint only initiates cancellation; the actual status must be verified via order status checks or WebSocket subscription.
#'
#' ## Description
#' This endpoint allows users to cancel a previously placed stop order identified by its `orderId`, which is the unique identifier assigned by the KuCoin system upon order creation. Stop orders are conditional orders that trigger when the market price reaches a specified `stopPrice`. The function sends a DELETE request to the KuCoin API and returns confirmation details upon successful initiation of the cancellation. The maximum number of untriggered stop orders per trading pair is 20, and this endpoint helps manage that limit by removing specific orders.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `orderId` is a non-empty string.
#' 2. **Request Construction**: Builds the endpoint URL with `orderId` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the DELETE method and endpoint.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, validates success, and returns a `data.table` with `cancelledOrderIds`.
#'
#' ## API Details
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v1/stop-order/{orderId}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: cancelStopOrderByOrderId
#' - **Official Documentation**: [KuCoin Cancel Stop Order By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/cancel-stop-order-by-orderld)
#'
#' ## Request
#' ### Path Parameters
#' - `orderId`: String (required) - The unique order ID generated by the trading system (e.g., "671124f9365ccb00073debd4").
#'
#' ### Example Request
#' ```bash
#' curl --location --request DELETE 'https://api.kucoin.com/api/v1/stop-order/671124f9365ccb00073debd4'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `cancelledOrderIds`: Array[String] (required) - Array of order IDs that were cancelled (typically a single ID for this endpoint).
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "cancelledOrderIds": [
#'       "671124f9365ccb00073debd4"
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to cancel (e.g., "671124f9365ccb00073debd4"). Required.
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `cancelledOrderIds` (character): The ID of the cancelled order.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Cancel a stop order by orderId
#'   cancellation <- await(cancel_stop_order_by_order_id_impl(
#'     orderId = "671124f9365ccb00073debd4"
#'   ))
#'   print(cancellation)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#'
#' # Expected Output:
#' #    cancelledOrderIds
#' # 1: 671124f9365ccb00073debd4
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort
#' @export
cancel_stop_order_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v1/stop-order/", orderId)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", endpoint, NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        result_dt <- data.table::data.table(
            cancelledOrderIds = parsed_response$data$cancelledOrderIds
        )

        return(result_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in cancel_stop_order_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Get Stop Orders List (Implementation)
#'
#' Retrieves a paginated list of untriggered stop orders from the KuCoin Spot trading system asynchronously.
#' This function constructs a GET request to the KuCoin API and returns a promise that resolves to a `data.table`
#' containing details of stop orders, sorted by the latest update time in descending order.
#'
#' ## Description
#' This endpoint fetches a list of stop orders that have not yet been triggered. Stop orders are conditional orders
#' that become active when the market price reaches a specified `stopPrice`. The list is paginated and sorted to show
#' the most recent orders first. Users can filter the results using various query parameters such as `symbol`, `side`,
#' `type`, and time range.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures that provided parameters are valid, such as `symbol`, `side`, `type`, and pagination settings.
#' 2. **Request Construction**: Builds the endpoint URL with query parameters for filtering and pagination.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, converts the `items` array to a `data.table`, and adds datetime columns for `createdAt` and `orderTime`.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v1/stop-order`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 8
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getStopOrdersList
#' - **Official Documentation**: [KuCoin Get Stop Orders List](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-stop-orders-list)
#'
#' ## Request
#' ### Query Parameters
#' - `symbol`: String (optional) - Filter by trading pair (e.g., "BTC-USDT").
#' - `side`: Enum<String> (optional) - Filter by order side: "buy" or "sell".
#' - `type`: Enum<String> (optional) - Filter by order type: "limit", "market", "limit_stop", "market_stop".
#' - `tradeType`: Enum<String> (optional) - Filter by trade type: "TRADE", "MARGIN_TRADE", "MARGIN_ISOLATED_TRADE".
#' - `startAt`: Integer<int64> (optional) - Start time in milliseconds.
#' - `endAt`: Integer<int64> (optional) - End time in milliseconds.
#' - `currentPage`: Integer (optional) - Current page number.
#' - `orderIds`: String (optional) - Comma-separated list of order IDs.
#' - `pageSize`: Integer (optional) - Number of orders per page.
#' - `stop`: String (optional) - Filter by stop order type: "stop" or "oco".
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v1/stop-order?symbol=BTC-USDT&side=buy&pageSize=10'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `currentPage`: Integer - Current page number.
#'   - `pageSize`: Integer - Number of orders per page.
#'   - `totalNum`: Integer - Total number of stop orders.
#'   - `totalPage`: Integer - Total number of pages.
#'   - `items`: Array of objects - List of stop orders, each with fields such as:
#'     - `id`: String - Order ID.
#'     - `symbol`: String - Trading pair.
#'     - `userId`: String - User ID.
#'     - `status`: String - Order status.
#'     - `type`: String - Order type.
#'     - `side`: String - Order side.
#'     - `price`: String - Order price.
#'     - `size`: String - Order size.
#'     - `funds`: String - Order funds.
#'     - `stp`: String - Self Trade Prevention.
#'     - `timeInForce`: String - Time in force.
#'     - `cancelAfter`: Integer - Cancel after n seconds.
#'     - `postOnly`: Boolean - Post-only flag.
#'     - `hidden`: Boolean - Hidden order flag.
#'     - `iceberg`: Boolean - Iceberg order flag.
#'     - `visibleSize`: String - Visible size for iceberg orders.
#'     - `channel`: String - Order channel.
#'     - `clientOid`: String - Client order ID.
#'     - `remark`: String - Order remarks.
#'     - `tags`: String - Order tags.
#'     - `orderTime`: Integer - Order time in nanoseconds.
#'     - `domainId`: String - Domain ID.
#'     - `tradeSource`: String - Trade source.
#'     - `tradeType`: String - Trade type.
#'     - `feeCurrency`: String - Fee currency.
#'     - `takerFeeRate`: String - Taker fee rate.
#'     - `makerFeeRate`: String - Maker fee rate.
#'     - `createdAt`: Integer - Creation timestamp in milliseconds.
#'     - `stop`: String - Stop order type.
#'     - `stopTriggerTime`: Integer - Stop trigger time.
#'     - `stopPrice`: String - Stop price.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "currentPage": 1,
#'     "pageSize": 50,
#'     "totalNum": 1,
#'     "totalPage": 1,
#'     "items": [
#'       {
#'         "id": "vs8hoo8kqjnklv4m0038lrfq",
#'         "symbol": "KCS-USDT",
#'         "userId": "60fe4956c43cbc0006562c2c",
#'         "status": "NEW",
#'         "type": "limit",
#'         "side": "buy",
#'         "price": "0.01000000000000000000",
#'         "size": "0.01000000000000000000",
#'         "funds": null,
#'         "stp": null,
#'         "timeInForce": "GTC",
#'         "cancelAfter": -1,
#'         "postOnly": false,
#'         "hidden": false,
#'         "iceberg": false,
#'         "visibleSize": null,
#'         "channel": "API",
#'         "clientOid": "404814a0fb4311eb9098acde48001122",
#'         "remark": null,
#'         "tags": null,
#'         "orderTime": 1628755183702150167,
#'         "domainId": "kucoin",
#'         "tradeSource": "USER",
#'         "tradeType": "TRADE",
#'         "feeCurrency": "USDT",
#'         "takerFeeRate": "0.00200000000000000000",
#'         "makerFeeRate": "0.00200000000000000000",
#'         "createdAt": 1628755183704,
#'         "stop": "loss",
#'         "stopTriggerTime": null,
#'         "stopPrice": "10.00000000000000000000"
#'       }
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param query Named list; query parameters for filtering and pagination (e.g., `list(symbol = "BTC-USDT", side = "buy", pageSize = 10)`). Optional.
#' @return Promise resolving to a `data.table` containing stop order details, with the following columns:
#'   - `id` (character): Unique order ID assigned by KuCoin.
#'   - `symbol` (character): Trading pair (e.g., "KCS-USDT").
#'   - `userId` (character): User ID associated with the order.
#'   - `status` (character): Order status (e.g., "NEW", "TRIGGERED").
#'   - `type` (character): Order type (e.g., "limit", "market").
#'   - `side` (character): Order side ("buy" or "sell").
#'   - `price` (character): Order price.
#'   - `size` (character): Order size.
#'   - `funds` (character or NA): Order funds (NULL for untriggered orders).
#'   - `stp` (character or NA): Self Trade Prevention strategy (e.g., "DC", "CO", "CN", "CB").
#'   - `timeInForce` (character): Time in force (e.g., "GTC", "GTT", "IOC", "FOK").
#'   - `cancelAfter` (integer): Seconds until cancellation for GTT (-1 if not applicable).
#'   - `postOnly` (logical): Whether the order is post-only.
#'   - `hidden` (logical): Whether the order is hidden.
#'   - `iceberg` (logical): Whether the order is an iceberg order.
#'   - `visibleSize` (character or NA): Visible size for iceberg orders.
#'   - `channel` (character): Order source (e.g., "API").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `remark` (character or NA): Order remarks.
#'   - `tags` (character or NA): Order tags.
#'   - `orderTime` (numeric): Order creation time in nanoseconds.
#'   - `domainId` (character): Domain ID (e.g., "kucoin").
#'   - `tradeSource` (character): Trade source (e.g., "USER").
#'   - `tradeType` (character): Trade type (e.g., "TRADE").
#'   - `feeCurrency` (character): Currency used for fees.
#'   - `takerFeeRate` (character): Taker fee rate.
#'   - `makerFeeRate` (character): Maker fee rate.
#'   - `createdAt` (integer): Creation timestamp in milliseconds.
#'   - `stop` (character): Stop order type (e.g., "loss", "entry").
#'   - `stopTriggerTime` (integer or NA): Trigger time in milliseconds (NULL if untriggered).
#'   - `stopPrice` (character): Stop price.
#'   - `createdAtDatetime` (POSIXct): Creation time in UTC (derived from `createdAt`).
#'   - `orderTimeDatetime` (POSIXct): Order placement time in UTC (derived from `orderTime`).
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve stop orders list for BTC-USDT
#'   stop_orders <- await(get_stop_orders_list_impl(
#'     query = list(symbol = "BTC-USDT", side = "buy", pageSize = 10)
#'   ))
#'   print(stop_orders)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_stop_orders_list_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    query = list()
) {
    tryCatch({
        # Validate parameters
        if (!is.list(query)) {
            rlang::abort("Parameter 'query' must be a named list.")
        }
        if ("symbol" %in% names(query) && !is.null(query$symbol) && !verify_symbol(query$symbol)) {
            rlang::abort("Parameter 'query$symbol', if provided, must be a valid trading pair (e.g., 'BTC-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v1/stop-order"
        query_string <- build_query(query)
        full_url <- paste0(base_url, endpoint, query_string)

        # Generate authentication headers
        headers <- await(build_headers("GET", paste0(endpoint, query_string), NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        if (length(parsed_response$data$items) == 0) {
            stop_orders_dt <- data.table::data.table(
                id = character(),
                symbol = character(),
                userId = character(),
                status = character(),
                type = character(),
                side = character(),
                price = character(),
                size = character(),
                funds = character(),
                stp = character(),
                timeInForce = character(),
                cancelAfter = integer(),
                postOnly = logical(),
                hidden = logical(),
                iceberg = logical(),
                visibleSize = character(),
                channel = character(),
                clientOid = character(),
                remark = character(),
                tags = character(),
                orderTime = numeric(),
                domainId = character(),
                tradeSource = character(),
                tradeType = character(),
                feeCurrency = character(),
                takerFeeRate = character(),
                makerFeeRate = character(),
                createdAt = integer(),
                stop = character(),
                stopTriggerTime = integer(),
                stopPrice = character(),
                createdAtDatetime = as.POSIXct(character()),
                orderTimeDatetime = as.POSIXct(character())
            )
        } else {
            stop_orders_dt <- data.table::rbindlist(parsed_response$data$items, fill = TRUE)
            stop_orders_dt[, createdAtDatetime := time_convert_from_kucoin(createdAt, unit = "ms")]
            stop_orders_dt[, orderTimeDatetime := time_convert_from_kucoin(orderTime, unit = "ns")]
        }

        return(stop_orders_dt)
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_stop_orders_list_impl: %s", conditionMessage(e)))
    })
})

#' Get Stop Order By OrderId (Implementation)
#'
#' Retrieves detailed information for a single stop order using its order ID from the KuCoin Spot trading system asynchronously.
#' This function constructs a GET request to the KuCoin API and returns a promise that resolves to a `data.table`
#' with comprehensive stop order details, including additional UTC datetime columns derived from timestamps.
#'
#' ## Description
#' This endpoint fetches data for a specific stop order identified by its `orderId`, which is the unique identifier
#' assigned by the KuCoin system when the order is created. The stop order can be in various states, such as "NEW"
#' (untriggered) or "TRIGGERED" (activated).
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `orderId` is a non-empty string.
#' 2. **Request Construction**: Builds the endpoint URL with `orderId` as a path parameter.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, converts the `data` object to a `data.table`, and adds `createdAtDatetime` and `orderTimeDatetime` columns.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v1/stop-order/{orderId}`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getStopOrderByOrderId
#' - **Official Documentation**: [KuCoin Get Stop Order By OrderId](https://www.kucoin.com/docs-new/rest/spot-trading/orders/get-stop-order-by-orderld)
#'
#' ## Request
#' ### Path Parameters
#' - `orderId`: String (required) - The unique order ID generated by the trading system (e.g., "vs8hoo8q2ceshiue003b67c0").
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v1/stop-order/vs8hoo8q2ceshiue003b67c0'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Stop order details with fields such as:
#'   - `id`: String - Order ID.
#'   - `symbol`: String - Trading pair.
#'   - `userId`: String - User ID.
#'   - `status`: String - Order status.
#'   - `type`: String - Order type.
#'   - `side`: String - Order side.
#'   - `price`: String - Order price.
#'   - `size`: String - Order size.
#'   - `funds`: String - Order funds.
#'   - `stp`: String - Self Trade Prevention.
#'   - `timeInForce`: String - Time in force.
#'   - `cancelAfter`: Integer - Cancel after n seconds.
#'   - `postOnly`: Boolean - Post-only flag.
#'   - `hidden`: Boolean - Hidden order flag.
#'   - `iceberg`: Boolean - Iceberg order flag.
#'   - `visibleSize`: String - Visible size for iceberg orders.
#'   - `channel`: String - Order channel.
#'   - `clientOid`: String - Client order ID.
#'   - `remark`: String - Order remarks.
#'   - `tags`: String - Order tags.
#'   - `orderTime`: Integer - Order time in nanoseconds.
#'   - `domainId`: String - Domain ID.
#'   - `tradeSource`: String - Trade source.
#'   - `tradeType`: String - Trade type.
#'   - `feeCurrency`: String - Fee currency.
#'   - `takerFeeRate`: String - Taker fee rate.
#'   - `makerFeeRate`: String - Maker fee rate.
#'   - `createdAt`: Integer - Creation timestamp in milliseconds.
#'   - `stop`: String - Stop order type.
#'   - `stopTriggerTime`: Integer - Stop trigger time.
#'   - `stopPrice`: String - Stop price.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "id": "vs8hoo8q2ceshiue003b67c0",
#'     "symbol": "KCS-USDT",
#'     "userId": "60fe4956c43cbc0006562c2c",
#'     "status": "NEW",
#'     "type": "limit",
#'     "side": "buy",
#'     "price": "0.01000000000000000000",
#'     "size": "0.01000000000000000000",
#'     "funds": null,
#'     "stp": null,
#'     "timeInForce": "GTC",
#'     "cancelAfter": -1,
#'     "postOnly": false,
#'     "hidden": false,
#'     "iceberg": false,
#'     "visibleSize": null,
#'     "channel": "API",
#'     "clientOid": "40e0eb9efe6311eb8e58acde48001122",
#'     "remark": null,
#'     "tags": null,
#'     "orderTime": 1629098781127530345,
#'     "domainId": "kucoin",
#'     "tradeSource": "USER",
#'     "tradeType": "TRADE",
#'     "feeCurrency": "USDT",
#'     "takerFeeRate": "0.00200000000000000000",
#'     "makerFeeRate": "0.00200000000000000000",
#'     "createdAt": 1629098781128,
#'     "stop": "loss",
#'     "stopTriggerTime": null,
#'     "stopPrice": "10.00000000000000000000"
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param orderId Character string; the unique order ID to retrieve (e.g., "vs8hoo8q2ceshiue003b67c0"). Required.
#' @return Promise resolving to a `data.table` with one row containing stop order details, with the following columns:
#'   - `id` (character): Unique order ID assigned by KuCoin.
#'   - `symbol` (character): Trading pair (e.g., "KCS-USDT").
#'   - `userId` (character): User ID associated with the order.
#'   - `status` (character): Order status (e.g., "NEW", "TRIGGERED").
#'   - `type` (character): Order type (e.g., "limit", "market").
#'   - `side` (character): Order side ("buy" or "sell").
#'   - `price` (character): Order price.
#'   - `size` (character): Order size.
#'   - `funds` (character or NA): Order funds (NULL for untriggered orders).
#'   - `stp` (character or NA): Self Trade Prevention strategy (e.g., "DC", "CO", "CN", "CB").
#'   - `timeInForce` (character): Time in force (e.g., "GTC", "GTT", "IOC", "FOK").
#'   - `cancelAfter` (integer): Seconds until cancellation for GTT (-1 if not applicable).
#'   - `postOnly` (logical): Whether the order is post-only.
#'   - `hidden` (logical): Whether the order is hidden.
#'   - `iceberg` (logical): Whether the order is an iceberg order.
#'   - `visibleSize` (character or NA): Visible size for iceberg orders.
#'   - `channel` (character): Order source (e.g., "API").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `remark` (character or NA): Order remarks.
#'   - `tags` (character or NA): Order tags.
#'   - `orderTime` (numeric): Order creation time in nanoseconds.
#'   - `domainId` (character): Domain ID (e.g., "kucoin").
#'   - `tradeSource` (character): Trade source (e.g., "USER").
#'   - `tradeType` (character): Trade type (e.g., "TRADE").
#'   - `feeCurrency` (character): Currency used for fees.
#'   - `takerFeeRate` (character): Taker fee rate.
#'   - `makerFeeRate` (character): Maker fee rate.
#'   - `createdAt` (integer): Creation timestamp in milliseconds.
#'   - `stop` (character): Stop order type (e.g., "loss", "entry").
#'   - `stopTriggerTime` (integer or NA): Trigger time in milliseconds (NULL if untriggered).
#'   - `stopPrice` (character): Stop price.
#'   - `createdAtDatetime` (POSIXct): Creation time in UTC (derived from `createdAt`).
#'   - `orderTimeDatetime` (POSIXct): Order placement time in UTC (derived from `orderTime`).
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve stop order details by orderId
#'   stop_order_details <- await(get_stop_order_by_order_id_impl(
#'     orderId = "vs8hoo8q2ceshiue003b67c0"
#'   ))
#'   print(stop_order_details)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_stop_order_by_order_id_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    orderId
) {
    tryCatch({
        # Validate parameters
        if (is.null(orderId) || !is.character(orderId) || nchar(orderId) == 0) {
            rlang::abort("Parameter 'orderId' must be a non-empty string.")
        }

        # Construct endpoint
        endpoint <- paste0("/api/v1/stop-order/", orderId)
        full_url <- paste0(base_url, endpoint)

        # Generate authentication headers
        headers <- await(build_headers("GET", endpoint, NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        stop_order_details <- data.table::rbindlist(list(parsed_response$data), fill = TRUE)

        # Add datetime columns from millisecond and nanosecond timestamps
        stop_order_details[, createdAtDatetime := time_convert_from_kucoin(createdAt, unit = "ms")]
        stop_order_details[, orderTimeDatetime := time_convert_from_kucoin(orderTime, unit = "ns")]

        return(stop_order_details)
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_stop_order_by_order_id_impl: %s", conditionMessage(e)))
    })
})

#' Get Stop Order By ClientOid (Implementation)
#'
#' Retrieves detailed information for a single stop order using its client order ID (`clientOid`) from the KuCoin Spot trading system asynchronously.
#' This function constructs a GET request to the KuCoin API and returns a promise that resolves to a `data.table`
#' with comprehensive stop order details, including additional UTC datetime columns derived from timestamps.
#'
#' ## Description
#' This endpoint fetches data for a specific stop order identified by its `clientOid`, a unique identifier assigned
#' by the user when placing the order. The stop order can be in various states, such as "NEW" (untriggered) or
#' "TRIGGERED" (activated).
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `clientOid` is a non-empty string and `symbol` (if provided) is a valid trading pair.
#' 2. **Request Construction**: Builds the endpoint URL with query parameters `clientOid` and optionally `symbol`.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the GET method and endpoint.
#' 4. **API Request**: Sends a GET request to the KuCoin API with a 3-second timeout.
#' 5. **Response Processing**: Parses the response, converts the `data` array to a `data.table`, and adds `createdAtDatetime` and `orderTimeDatetime` columns.
#'
#' ## API Details
#' - **Endpoint**: `GET https://api.kucoin.com/api/v1/stop-order/queryOrderByClientOid`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: General
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: getStopOrderByClientOid
#' - **Official Documentation**: [KuCoin Get Stop Order By ClientOid](https://www.kucoin.com/docs-new/rest/spot-trading/get-stop-order-by-clientoid)
#'
#' ## Request
#' ### Query Parameters
#' - `clientOid`: String (required) - The unique client order ID (e.g., "2b700942b5db41cebe578cff48960e09").
#' - `symbol`: String (optional) - The trading pair symbol (e.g., "KCS-USDT").
#'
#' ### Example Request
#' ```bash
#' curl --location --request GET 'https://api.kucoin.com/api/v1/stop-order/queryOrderByClientOid?clientOid=404814a0fb4311eb9098acde48001122&symbol=KCS-USDT'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Array of objects (required) - List of stop order details (typically one item), each with fields such as:
#'   - `id`: String - Order ID.
#'   - `symbol`: String - Trading pair.
#'   - `userId`: String - User ID.
#'   - `status`: String - Order status.
#'   - `type`: String - Order type.
#'   - `side`: String - Order side.
#'   - `price`: String - Order price.
#'   - `size`: String - Order size.
#'   - `funds`: String - Order funds.
#'   - `stp`: String - Self Trade Prevention.
#'   - `timeInForce`: String - Time in force.
#'   - `cancelAfter`: Integer - Cancel after n seconds.
#'   - `postOnly`: Boolean - Post-only flag.
#'   - `hidden`: Boolean - Hidden order flag.
#'   - `iceberg`: Boolean - Iceberg order flag.
#'   - `visibleSize`: String - Visible size for iceberg orders.
#'   - `channel`: String - Order channel.
#'   - `clientOid`: String - Client order ID.
#'   - `remark`: String - Order remarks.
#'   - `tags`: String - Order tags.
#'   - `orderTime`: Integer - Order time in nanoseconds.
#'   - `domainId`: String - Domain ID.
#'   - `tradeSource`: String - Trade source.
#'   - `tradeType`: String - Trade type.
#'   - `feeCurrency`: String - Fee currency.
#'   - `takerFeeRate`: String - Taker fee rate.
#'   - `makerFeeRate`: String - Maker fee rate.
#'   - `createdAt`: Integer - Creation timestamp in milliseconds.
#'   - `stop`: String - Stop order type.
#'   - `stopTriggerTime`: Integer - Stop trigger time.
#'   - `stopPrice`: String - Stop price.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": [
#'     {
#'       "id": "vs8hoo8os561f5np0032vngj",
#'       "symbol": "KCS-USDT",
#'       "userId": "60fe4956c43cbc0006562c2c",
#'       "status": "NEW",
#'       "type": "limit",
#'       "side": "buy",
#'       "price": "0.01000000000000000000",
#'       "size": "0.01000000000000000000",
#'       "funds": null,
#'       "stp": null,
#'       "timeInForce": "GTC",
#'       "cancelAfter": -1,
#'       "postOnly": false,
#'       "hidden": false,
#'       "iceberg": false,
#'       "visibleSize": null,
#'       "channel": "API",
#'       "clientOid": "2b700942b5db41cebe578cff48960e09",
#'       "remark": null,
#'       "tags": null,
#'       "orderTime": 1629020492834532600,
#'       "domainId": "kucoin",
#'       "tradeSource": "USER",
#'       "tradeType": "TRADE",
#'       "feeCurrency": "USDT",
#'       "takerFeeRate": "0.00200000000000000000",
#'       "makerFeeRate": "0.00200000000000000000",
#'       "createdAt": 1629020492837,
#'       "stop": "loss",
#'       "stopTriggerTime": null,
#'       "stopPrice": "1.00000000000000000000"
#'     }
#'   ]
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param clientOid Character string; the unique client order ID to retrieve (e.g., "2b700942b5db41cebe578cff48960e09"). Required.
#' @param symbol Character string; the trading pair symbol (e.g., "KCS-USDT"). Optional.
#' @return Promise resolving to a `data.table` with typically one row containing stop order details, with the following columns:
#'   - `id` (character): Unique order ID assigned by KuCoin.
#'   - `symbol` (character): Trading pair (e.g., "KCS-USDT").
#'   - `userId` (character): User ID associated with the order.
#'   - `status` (character): Order status (e.g., "NEW", "TRIGGERED").
#'   - `type` (character): Order type (e.g., "limit", "market").
#'   - `side` (character): Order side ("buy" or "sell").
#'   - `price` (character): Order price.
#'   - `size` (character): Order size.
#'   - `funds` (character or NA): Order funds (NULL for untriggered orders).
#'   - `stp` (character or NA): Self Trade Prevention strategy (e.g., "DC", "CO", "CN", "CB").
#'   - `timeInForce` (character): Time in force (e.g., "GTC", "GTT", "IOC", "FOK").
#'   - `cancelAfter` (integer): Seconds until cancellation for GTT (-1 if not applicable).
#'   - `postOnly` (logical): Whether the order is post-only.
#'   - `hidden` (logical): Whether the order is hidden.
#'   - `iceberg` (logical): Whether the order is an iceberg order.
#'   - `visibleSize` (character or NA): Visible size for iceberg orders.
#'   - `channel` (character): Order source (e.g., "API").
#'   - `clientOid` (character): Client-assigned order ID.
#'   - `remark` (character or NA): Order remarks.
#'   - `tags` (character or NA): Order tags.
#'   - `orderTime` (numeric): Order creation time in nanoseconds.
#'   - `domainId` (character): Domain ID (e.g., "kucoin").
#'   - `tradeSource` (character): Trade source (e.g., "USER").
#'   - `tradeType` (character): Trade type (e.g., "TRADE").
#'   - `feeCurrency` (character): Currency used for fees.
#'   - `takerFeeRate` (character): Taker fee rate.
#'   - `makerFeeRate` (character): Maker fee rate.
#'   - `createdAt` (integer): Creation timestamp in milliseconds.
#'   - `stop` (character): Stop order type (e.g., "loss", "entry").
#'   - `stopTriggerTime` (integer or NA): Trigger time in milliseconds (NULL if untriggered).
#'   - `stopPrice` (character): Stop price.
#'   - `createdAtDatetime` (POSIXct): Creation time in UTC (derived from `createdAt`).
#'   - `orderTimeDatetime` (POSIXct): Order placement time in UTC (derived from `orderTime`).
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Retrieve stop order details by clientOid
#'   stop_order_details <- await(get_stop_order_by_client_oid_impl(
#'     clientOid = "2b700942b5db41cebe578cff48960e09",
#'     symbol = "KCS-USDT"
#'   ))
#'   print(stop_order_details)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table rbindlist
#' @importFrom httr GET timeout
#' @importFrom rlang abort
#' @export
get_stop_order_by_client_oid_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    clientOid,
    symbol = NULL
) {
    tryCatch({
        # Validate parameters
        if (is.null(clientOid) || !is.character(clientOid) || nchar(clientOid) == 0) {
            rlang::abort("Parameter 'clientOid' must be a non-empty string.")
        }
        if (!is.null(symbol) && !verify_symbol(symbol)) {
            rlang::abort("Parameter 'symbol', if provided, must be a valid trading pair (e.g., 'KCS-USDT').")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v1/stop-order/queryOrderByClientOid"
        query_params <- list(clientOid = clientOid)
        if (!is.null(symbol)) {
            query_params$symbol <- symbol
        }
        query_string <- build_query(query_params)
        full_url <- paste0(base_url, endpoint, query_string)

        # Generate authentication headers
        headers <- await(build_headers("GET", paste0(endpoint, query_string), NULL, keys))

        # Send GET request
        response <- httr::GET(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Convert response data to data.table
        if (length(parsed_response$data) == 0) {
            stop_order_details <- data.table::data.table(
                id = character(),
                symbol = character(),
                userId = character(),
                status = character(),
                type = character(),
                side = character(),
                price = character(),
                size = character(),
                funds = character(),
                stp = character(),
                timeInForce = character(),
                cancelAfter = integer(),
                postOnly = logical(),
                hidden = logical(),
                iceberg = logical(),
                visibleSize = character(),
                channel = character(),
                clientOid = character(),
                remark = character(),
                tags = character(),
                orderTime = numeric(),
                domainId = character(),
                tradeSource = character(),
                tradeType = character(),
                feeCurrency = character(),
                takerFeeRate = character(),
                makerFeeRate = character(),
                createdAt = integer(),
                stop = character(),
                stopTriggerTime = integer(),
                stopPrice = character(),
                createdAtDatetime = as.POSIXct(character()),
                orderTimeDatetime = as.POSIXct(character())
            )
        } else {
            stop_order_details <- data.table::rbindlist(parsed_response$data, fill = TRUE)
            stop_order_details[, createdAtDatetime := time_convert_from_kucoin(createdAt, unit = "ms")]
            stop_order_details[, orderTimeDatetime := time_convert_from_kucoin(orderTime, unit = "ns")]
        }

        return(stop_order_details)
    }, error = function(e) {
        rlang::abort(sprintf("Error in get_stop_order_by_client_oid_impl: %s", conditionMessage(e)))
    })
})

#' Batch Cancel Stop Orders (Implementation)
#'
#' Cancels a batch of stop orders on the KuCoin Spot trading system asynchronously by sending a DELETE request to the `/api/v1/stop-order/cancel` endpoint.
#' Returns a `data.table` with the IDs of the canceled stop orders.
#'
#' ## What is a Stop Order and Batch Cancellation?
#' A stop order is a conditional order that triggers a market or limit order when a specified price (stop price) is reached, commonly used for:
#' - **Loss Limiting**: Sell an asset if its price drops to a threshold (e.g., sell BTC at $48,000 if it falls from $50,000).
#' - **Breakout Trading**: Buy an asset if its price rises past a resistance level (e.g., buy BTC at $52,000 if it breaks $51,000).
#' Batch cancellation allows you to cancel multiple stop orders at once, which is useful for:
#' - **Portfolio Adjustment**: Clear all stop orders for a symbol (e.g., "BTC-USDT") if market conditions shift unexpectedly.
#' - **Strategy Reset**: Cancel outdated stop orders across multiple pairs or IDs when refining your trading plan.
#' - **Risk Management**: Remove pending stops during high volatility to avoid unintended triggers (e.g., canceling stops on ETH-BTC during a flash crash).
#' For example, if you have stop orders at $48,000 and $47,000 for BTC-USDT but anticipate a rally, batch canceling them prevents premature sales.
#'
#' ## Description
#' This function cancels multiple stop orders using optional filters (`symbol`, `tradeType`, `orderIds`) via a DELETE request, returning the canceled order IDs in a `data.table`.
#'
#' ## Workflow
#' 1. **Parameter Validation**: Ensures `query` is a named list, validates `symbol` if provided, and checks `tradeType` enum.
#' 2. **Request Construction**: Builds the endpoint URL with query parameters (`symbol`, `tradeType`, `orderIds`) using `build_query`.
#' 3. **Authentication**: Generates private API headers using `build_headers()` with the DELETE method and endpoint.
#' 4. **API Request**: Sends a DELETE request to the KuCoin API with a 3-second timeout via `httr::DELETE`.
#' 5. **Response Processing**: Parses the response with `process_kucoin_response`, confirms success ("200000"), and converts the `cancelledOrderIds` array to a `data.table` column as a list.
#'
#' ## API Details
#' - **Endpoint**: `DELETE https://api.kucoin.com/api/v1/stop-order/cancel`
#' - **Domain**: Spot
#' - **API Channel**: Private
#' - **API Permission**: Spot
#' - **Rate Limit Pool**: Spot
#' - **Rate Limit Weight**: 3
#' - **SDK Service**: Spot
#' - **SDK Sub-Service**: Order
#' - **SDK Method Name**: batchCancelStopOrder
#' - **Official Documentation**: [KuCoin Batch Cancel Stop Orders](https://www.kucoin.com/docs-new/rest/spot-trading/orders/batch-cancel-stop-orders)
#'
#' ## Request
#' ### Query Parameters
#' - `symbol`: String (optional) - Filter by trading pair symbol (e.g., "ETH-BTC"). Cancels all stop orders for this symbol if specified.
#' - `tradeType`: Enum<String> (optional) - Transaction type: "TRADE" (Spot), "MARGIN_TRADE" (Cross Margin), "MARGIN_ISOLATED_TRADE" (Isolated Margin). Defaults to "TRADE".
#' - `orderIds`: String (optional) - Comma-separated list of stop order IDs (e.g., "5bd6e9286d99522a52e458de,5bd6e9286d99522a52e458df").
#'
#' ### Example Request
#' ```bash
#' curl --location --request DELETE 'https://api.kucoin.com/api/v1/stop-order/cancel?symbol=ETH-BTC&tradeType=TRADE&orderIds=5bd6e9286d99522a52e458de,5bd6e9286d99522a52e458df'
#' ```
#'
#' ## Response
#' ### HTTP Code: 200
#' - **Content Type**: `application/json`
#'
#' ### Data Schema
#' - `code`: String (required) - Response code ("200000" indicates success).
#' - `data`: Object (required) - Contains:
#'   - `cancelledOrderIds`: Array[String] (required) - List of canceled stop order IDs.
#'
#' ### JSON Response Example
#' ```json
#' {
#'   "code": "200000",
#'   "data": {
#'     "cancelledOrderIds": [
#'       "671124f9365ccb00073debd4"
#'     ]
#'   }
#' }
#' ```
#'
#' @param keys List; API configuration parameters from `get_api_keys()`. Defaults to `get_api_keys()`.
#' @param base_url Character string; base URL for the KuCoin API. Defaults to `get_base_url()`.
#' @param query Named list; optional query parameters for filtering (e.g., `list(symbol = "ETH-BTC", orderIds = "5bd6e9286d99522a52e458de,5bd6e9286d99522a52e458df")`).
#' @return Promise resolving to a `data.table` with one row containing:
#'   - `cancelledOrderIds` (list): A list of character strings representing the IDs of the canceled stop orders.
#' @examples
#' \dontrun{
#' library(coro)
#' library(data.table)
#'
#' main_async <- coro::async(function() {
#'   # Batch cancel stop orders for ETH-BTC
#'   canceled_orders <- await(batch_cancel_stop_orders_impl(
#'     query = list(
#'       symbol = "ETH-BTC",
#'       tradeType = "TRADE",
#'       orderIds = "5bd6e9286d99522a52e458de,5bd6e9286d99522a52e458df"
#'     )
#'   ))
#'   print(canceled_orders)
#' })
#'
#' # Run the async function
#' main_async()
#' while (!later::loop_empty()) later::run_now()
#' }
#' @importFrom coro async await
#' @importFrom data.table data.table
#' @importFrom httr DELETE timeout
#' @importFrom rlang abort arg_match0
#' @export
batch_cancel_stop_orders_impl <- coro::async(function(
    keys = get_api_keys(),
    base_url = get_base_url(),
    query = list()
) {
    tryCatch({
        # Validate parameters
        if (!is.list(query)) {
            rlang::abort("Parameter 'query' must be a named list.")
        }
        if ("symbol" %in% names(query) && !is.null(query$symbol) && !verify_symbol(query$symbol)) {
            rlang::abort("Parameter 'query$symbol', if provided, must be a valid trading pair (e.g., 'ETH-BTC').")
        }
        if ("tradeType" %in% names(query) && !is.null(query$tradeType)) {
            query$tradeType <- rlang::arg_match0(
                query$tradeType,
                c("TRADE", "MARGIN_TRADE", "MARGIN_ISOLATED_TRADE"),
                "query$tradeType"
            )
        }
        if ("orderIds" %in% names(query) && (!is.character(query$orderIds) || nchar(query$orderIds) == 0)) {
            rlang::abort("Parameter 'query$orderIds', if provided, must be a non-empty comma-separated string.")
        }

        # Construct endpoint and query string
        endpoint <- "/api/v1/stop-order/cancel"
        query_string <- build_query(query)
        full_url <- paste0(base_url, endpoint, query_string)

        # Generate authentication headers
        headers <- await(build_headers("DELETE", paste0(endpoint, query_string), NULL, keys))

        # Send DELETE request
        response <- httr::DELETE(
            url = full_url,
            headers,
            httr::timeout(3)
        )

        # Process response
        parsed_response <- process_kucoin_response(response, full_url)
        if (parsed_response$code != "200000") {
            rlang::abort(sprintf("API error: %s - %s", parsed_response$code, parsed_response$msg))
        }

        # Return as data.table
        return(data.table::data.table(cancelledOrderIds = list(parsed_response$data$cancelledOrderIds)))
    }, error = function(e) {
        rlang::abort(sprintf("Error in batch_cancel_stop_orders_impl: %s", conditionMessage(e)))
    })
})
